const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

// Garde titres et descriptions dans les longueurs affichées par Google.
const fit = (max, ...opts) => opts.find((o) => o.length <= max) ?? opts.at(-1);
const kwFit = (e, sep, f) => fit(158, ...[3, 2, 1, 0].map((n) => f(n ? sep + e.kw.slice(0, n).join(', ') : '')));

export default {
  code: 'en',
  hreflang: 'en',
  ogLocale: 'en_GB',
  prefix: '/en',
  label: 'EN',
  langName: 'English',

  slugs: {
    zones: 'areas',
    zone: 'refrigeration-',
    contact: 'contact',
    blog: 'advice',
    legal: 'legal-notice',
    privacy: 'privacy',
  },

  t: {
    skip: 'Skip to content',
    available: 'Available 24/7',
    regions: 'Wallonia · Brussels · Flanders',
    call: 'Call',
    callNumber: (n) => `Call ${n}`,
    quote: 'Request a quote',
    quoteShort: 'Quote',
    generic: { name: 'refrigeration or AC', your: 'your equipment' },
    whatsapp: 'WhatsApp',
    menu: 'Menu',
    subMenu: 'Open submenu',
    home: 'Home',
    zones: 'Areas',
    blog: 'Advice',
    contact: 'Contact',
    langSwitch: 'Language',
    learnMore: 'Learn more',
    readMore: 'Read the article',
    allZones: 'All areas covered',
    footerTagline: 'Certified refrigeration engineers in Belgium. Repair, maintenance and installation of refrigeration and air conditioning, 24 hours a day, 7 days a week.',
    footerServices: 'Services',
    footerZones: 'Areas covered',
    footerContact: 'Contact',
    legal: 'Legal notice',
    privacy: 'Privacy',
    rights: 'All rights reserved.',
    ctaTitle: "A breakdown or a project? Let's talk.",
    ctaText: 'Call us, message us on WhatsApp or send your request: we reply quickly, at any hour.',
    zonesTitle: 'Areas covered',
    zonesLead: 'FrigAirco travels throughout Belgium: Wallonia, Brussels and Flanders.',
    groups: { region: 'Regions', wal: 'Towns in Wallonia', fla: 'Towns in Flanders' },
    faqTitle: 'Frequently asked questions',
    alsoTitle: (e) => `More for ${e.your}`,
    otherTitle: (a) => `${a.name}: other equipment`,
    whyTitle: 'Why choose FrigAirco',
    why: [
      ['clock', 'Fast response', 'A cooling breakdown cannot wait. We answer the phone and WhatsApp at any hour and arrange the visit as quickly as possible.'],
      ['shield', 'Certified engineers', 'F-Gas certified technicians and an approved company: your equipment is in qualified hands and compliant with regulations.'],
      ['award', 'Over 10 years of experience', 'From cold rooms to chillers, from bar fridges to heat pumps, we know the equipment and its faults, whatever the brand.'],
      ['users', 'Businesses and homeowners', 'Restaurants, butchers, bakeries, food shops, industry and offices, as well as houses and apartments.'],
    ],
    certTitle: 'Approvals and brands',
    certLead: 'Handling refrigerants is a regulated activity. FrigAirco holds the required approvals and works with the leading refrigeration and air conditioning brands.',
    certs: {
      'F-Gas': 'Technicians certified to handle refrigerants',
      'Vinçotte': 'Approval issued by an independent inspection body',
      'Bruxelles Environnement': 'Approved refrigeration company (Brussels Environment)',
    },
    brandsTitle: 'The brands we work with',
    reviewsTitle: 'Customer reviews',
    reviewsLead: 'What our customers say about FrigAirco on Google.',
    reviewsLink: 'See all reviews on Google',
    sectorsTitle: 'Our customers',
    sectors: ['Restaurants and hotels', 'Butchers', 'Bakeries', 'Food shops', 'Industry and logistics', 'Offices', 'Homeowners'],
    galleryTitle: 'Our work',
    toComplete: 'to be completed',
    notFoundTitle: 'Page not found',
    notFoundText: 'This page does not exist or has been moved.',
    notFoundBack: 'Back to the home page',
  },

  home: {
    title: 'FrigAirco | Refrigeration engineers in Belgium, 24/7 repair',
    desc: 'Certified refrigeration engineers in Belgium: cold room repair, air conditioning maintenance, heat pump installation. On call 24/7.',
    badge: 'Certified refrigeration engineers · Repair 24/7',
    h1: 'Your refrigeration engineer in Belgium, <em>24/7</em>',
    lead: 'Cold room repair, air conditioning maintenance, heat pump installation, commercial and industrial refrigeration maintenance: FrigAirco works across Wallonia, Brussels and Flanders, for businesses and homeowners.',
    checks: ['Call-outs anywhere in Belgium', 'Businesses and homeowners', 'F-Gas certified technicians', 'All brands'],
    stats: [['24/24', 'Repairs day and night'], ['7/7', 'Weekends and public holidays'], ['10+ years', 'of experience'], ['F-Gas', 'Certified technicians']],
    pickerTitle: 'Which equipment has broken down?',
    pickerNote: 'Choose your equipment or message us directly.',
    servicesTitle: 'Our refrigeration and air conditioning services',
    servicesLead: 'Three trades, one point of contact for all your refrigeration and air conditioning equipment.',
    equipTitle: 'All your refrigeration and air conditioning equipment',
    equipLead: 'Choose your equipment to see the details for repair, maintenance and installation.',
    faq: [
      ['Is FrigAirco really available 24 hours a day, 7 days a week?', 'Yes. For fridge, cold room and air conditioning repair we can be reached day and night, including weekends and public holidays.'],
      ['Which areas do you cover?', 'Wallonia, Brussels and Flanders: Hainaut, Walloon Brabant, Liège, Namur, Luxembourg province, Antwerp, Ghent, Leuven, Mechelen, Hasselt, Kortrijk and their surroundings.'],
      ['Which equipment do you work on?', 'Cold rooms and freezer rooms, freezers, commercial fridges, bar fridges and counter fridges, bakery and butcher counters, refrigerated displays, chest freezers, blast chillers, chillers, air conditioning and heat pumps.'],
      ['Do you also work for homeowners?', 'Yes. We install, maintain and repair air conditioning and heat pumps in private homes, alongside commercial and industrial refrigeration for businesses.'],
      ['Are your technicians certified?', 'Yes. Our engineers are F-Gas certified for handling refrigerants and the company is an approved refrigeration company.'],
      ['How do I get a quote?', 'Fill in the contact form, call us or message us on WhatsApp describing what you need. We get back to you quickly.'],
    ],
  },

  actions: {
    depannage: {
      slug: 'repair',
      nav: 'Repair',
      name: 'Repair',
      listKey: 'faults',
      hub: {
        title: 'Fridge, cold room and AC repair 24/7 in Belgium | FrigAirco',
        desc: 'Cold room repair, fridge repair, air conditioning repair, heat pump and chiller repair. Certified engineers on call 24/7 across Belgium.',
        h1: 'Fridge, cold room and air conditioning repair, 24/7',
        cardTitle: 'Refrigeration and AC repair 24/7',
        lead: 'A cooling breakdown cannot wait. FrigAirco repairs your refrigeration and air conditioning equipment day and night, weekends and public holidays included, anywhere in Belgium.',
        card: 'Cold room down, fridge no longer cooling, air conditioning out of order: an engineer you can reach day and night.',
      },
      pair: (e) => `${cap(e.name)} repair`,
      title: (e) => fit(62, `${cap(e.name)} repair 24/7 in Belgium | FrigAirco`, `${cap(e.name)} repair 24/7 | FrigAirco`),
      desc: (e) => kwFit(e, ': ', (k) => `Emergency ${e.name} repair, 24/7 anywhere in Belgium${k}. Certified refrigeration engineers, fast response.`),
      h1: (e) => `${cap(e.name)} repair 24/7`,
      lead: (e) => `Has ${e.your} broken down? Our refrigeration engineers are on call 24 hours a day, 7 days a week across Wallonia, Brussels and Flanders for ${e.name} repair: on-site diagnosis, repair and restart.`,
      listTitle: (e) => `${cap(e.name)} repair: the most common faults`,
      stepsTitle: (e) => `How does a ${e.name} repair work?`,
      steps: [
        ['You call or message us on WhatsApp', 'Describe the fault: we reply quickly, at any hour.'],
        ['On-site diagnosis', 'The technician finds the cause of the fault and explains what needs to be done.'],
        ['Repair', 'Replacing the faulty part, repairing the leak, recharging refrigerant if needed.'],
        ['Restart', 'Temperature checks and advice to keep the fault from coming back.'],
      ],
      faq: (e) => [
        [`Do you come out at night and at weekends for ${e.name} repair?`, `Yes. ${cap(e.name)} repair is available 24 hours a day, 7 days a week, public holidays included. Call us or send a WhatsApp message.`],
        [`Where do you offer ${e.name} repair?`, 'Anywhere in Belgium: Wallonia, Brussels and Flanders.'],
        ['What should I do while waiting for the technician?', 'Note the error code or the temperature shown, avoid restarting the unit several times in a row and, for food refrigeration, keep the doors closed to hold the cold.'],
      ],
    },
    entretien: {
      slug: 'maintenance',
      nav: 'Maintenance',
      name: 'Maintenance and servicing',
      listKey: 'upkeep',
      hub: {
        title: 'Fridge, cold room and AC maintenance | FrigAirco',
        desc: 'Air conditioning maintenance, cold room maintenance and heat pump servicing. One-off visits or a maintenance contract, anywhere in Belgium.',
        h1: 'Fridge, cold room and air conditioning maintenance',
        cardTitle: 'Refrigeration and AC maintenance',
        lead: 'Regular servicing prevents most breakdowns, cuts energy use and extends the life of your equipment. FrigAirco provides one-off servicing and maintenance contracts for your refrigeration and air conditioning equipment.',
        card: 'One-off servicing or a maintenance contract: fewer breakdowns, lower energy use, checks kept up to date.',
      },
      pair: (e) => `${cap(e.name)} maintenance`,
      title: (e) => fit(62, `${cap(e.name)} maintenance and servicing in Belgium | FrigAirco`, `${cap(e.name)} maintenance and servicing | FrigAirco`, `${cap(e.name)} maintenance | FrigAirco`),
      desc: (e) => kwFit(e, ': ', (k) => `${cap(e.name)} maintenance and servicing by certified engineers${k}. One-off visits or a maintenance contract, anywhere in Belgium.`),
      h1: (e) => `${cap(e.name)} maintenance and servicing`,
      lead: (e) => `Regular ${e.name} maintenance means fewer breakdowns, controlled energy use and equipment that lasts. FrigAirco provides one-off ${e.name} servicing and maintenance contracts, for businesses and homeowners.`,
      listTitle: (e) => `What ${e.name} maintenance includes`,
      extra: (e) => [`${cap(e.name)} maintenance contract`, `With a maintenance contract for ${e.your}, visits are scheduled in advance and the checks are recorded each time. We agree the frequency with you, depending on the equipment and how it is used.`],
      stepsTitle: (e) => `How does ${e.name} servicing work?`,
      steps: [
        ['Appointment', 'We pick a date that disrupts your business as little as possible.'],
        ['Technician visit', 'Cleaning, checks and adjustments following the list for your equipment.'],
        ['Report', 'You know what was done and what to keep an eye on.'],
        ['Follow-up', 'With a contract, the next visit is already scheduled.'],
      ],
      faq: (e) => [
        [`How often is ${e.name} maintenance needed?`, 'It depends on the equipment and how it is used. One visit a year is a common minimum; equipment that runs continuously, or in a greasy or dusty environment, needs more frequent visits. We agree the frequency with you.'],
        [`Is ${e.name} maintenance mandatory?`, 'Above a certain quantity of refrigerant, the F-Gas regulation requires periodic leak checks carried out by a certified technician. We tell you what applies to your equipment.'],
        [`Do you offer a ${e.name} maintenance contract?`, `Yes. The ${e.name} maintenance contract covers scheduled visits and follow-up of the equipment. Request a quote.`],
      ],
    },
    installation: {
      slug: 'installation',
      nav: 'Installation',
      name: 'Installation and assembly',
      listKey: 'setup',
      hub: {
        title: 'Cold room, AC and heat pump installation in Belgium | FrigAirco',
        desc: 'Cold room installation, air conditioning installation and heat pump installation. Design, assembly and commissioning by certified engineers.',
        h1: 'Cold room, air conditioning and heat pump installation',
        cardTitle: 'Refrigeration and AC installation',
        lead: 'Equipment that is properly sized and properly fitted uses less energy and breaks down less often. FrigAirco assesses what you need, supplies the equipment and handles assembly and commissioning.',
        card: 'Design, supply, assembly and commissioning of your refrigeration and air conditioning equipment.',
      },
      pair: (e) => `${cap(e.name)} installation`,
      title: (e) => fit(62, `${cap(e.name)} installation and assembly in Belgium | FrigAirco`, `${cap(e.name)} installation and assembly | FrigAirco`, `${cap(e.name)} installation | FrigAirco`),
      desc: (e) => kwFit(e, ': ', (k) => `${cap(e.name)} installation and assembly by certified engineers${k}. Survey, quote and commissioning anywhere in Belgium.`),
      h1: (e) => `${cap(e.name)} installation and assembly`,
      lead: (e) => `A new project or a unit at the end of its life to replace: FrigAirco handles ${e.name} installation from survey to commissioning, with careful ${e.name} assembly by certified refrigeration engineers.`,
      listTitle: (e) => `${cap(e.name)} installation: the steps`,
      stepsTitle: (e) => `Your ${e.name} assembly project, step by step`,
      steps: [
        ['Visit and survey', 'We look at the premises, your constraints and what you really need.'],
        ['Quote', 'A clear quote, with the proposed equipment and the planned work.'],
        ['Fitting and connections', 'Positioning, connections and finishing by our technicians.'],
        ['Commissioning', 'Tests, adjustments and a walk-through of how to use it.'],
      ],
      faq: (e) => [
        [`How much does ${e.name} installation cost?`, 'The price depends on the capacity, the equipment chosen and the layout of the premises. We prepare a quote once we have assessed what you need.'],
        ['Which brands do you install?', 'We work with Daikin, Mitsubishi Electric, Fujitsu, Bitzer and Danfoss among others, and we also service and repair other brands.'],
        [`Do you service the equipment after ${e.name} assembly?`, `Yes. After installation we can take care of ${e.name} maintenance, as well as repairs 24 hours a day, 7 days a week.`],
      ],
    },
  },

  equipment: {
    coldroom: {
      slug: 'cold-room',
      label: 'Cold room',
      name: 'cold room',
      title: 'Cold room and freezer room',
      your: 'your cold room',
      kw: ['walk-in cold room', 'freezer room', 'freezer', 'walk-in freezer'],
      short: 'Cold rooms, freezer rooms and freezers for hospitality, retail and industry.',
      intro: 'When a cold room stops, your stock is at risk within hours. FrigAirco looks after chilled cold rooms (0 to +8 °C), freezer rooms and freezers (down to −25 °C), whatever the brand and size.',
      faults: [
        'Cold room no longer reaching temperature, or an unstable temperature',
        'Freezer room or freezer icing up: evaporator blocked with ice, defrost fault',
        'Compressor that will not start, trips the breaker or runs non-stop',
        'Refrigerant leak, low gas charge',
        'Door, seals or hinges no longer closing, temperature alarm',
      ],
      upkeep: [
        'Cleaning the condenser and the evaporator',
        'Leak check of the circuit and check of operating pressures',
        'Checking the defrost, the fans and the condensate drain',
        'Checking door seals, hinges and frame heaters in freezer rooms',
        'Temperature readings and controller adjustment',
      ],
      setup: [
        'Assessment of the volume, temperatures and products to be stored',
        'Assembly of the insulated panels, door and floor',
        'Installation of the refrigeration unit and the evaporator',
        'Connection, vacuuming, refrigerant charging and commissioning',
        'Controller set-up and a walk-through of how to use it',
      ],
    },
    aircon: {
      slug: 'air-conditioning',
      label: 'Air conditioning',
      name: 'air conditioning',
      title: 'Air conditioning',
      your: 'your air conditioning',
      kw: ['AC', 'air con', 'split and multi-split systems', 'reversible air conditioning'],
      short: 'Air conditioning and reversible units for homes, offices, shops and restaurants.',
      intro: 'Air conditioning, AC or air con: FrigAirco looks after wall units, floor consoles, cassettes and ducted units, single-split and multi-split, for homeowners and businesses.',
      faults: [
        'Air conditioning no longer cooling or heating',
        'Unit leaking water indoors, blocked condensate drain',
        'Error code on the display, flashing light, remote control not responding',
        'Bad smells or unusual noise',
        'Outdoor unit not starting, low refrigerant charge',
      ],
      upkeep: [
        'Cleaning and disinfecting the filters and the indoor unit',
        'Cleaning the outdoor unit coil',
        'Leak check and pressure check of the circuit',
        'Checking the condensate drain',
        'Testing cooling and heating modes, checking supply air temperatures',
      ],
      setup: [
        'Visit and advice: capacity, position of the units, single or multi-split',
        'Assembly of the indoor and outdoor units',
        'Refrigerant pipework, condensate drain and power supply',
        'Vacuuming, commissioning and leak check',
        'A walk-through of the remote control and settings',
      ],
    },
    heatpump: {
      slug: 'heat-pump',
      label: 'Heat pump',
      name: 'heat pump',
      title: 'Heat pump',
      your: 'your heat pump',
      kw: ['air-to-air heat pump', 'air-to-water heat pump', 'reversible heat pump'],
      short: 'Air-to-air and air-to-water heat pumps to heat and cool while using less energy.',
      intro: 'A heat pump runs on a refrigeration circuit, which makes it a job for a refrigeration engineer. FrigAirco works on air-to-air and air-to-water heat pumps, for heating, cooling and hot water.',
      faults: [
        'Heat pump no longer heating, or heating poorly',
        'Outdoor unit covered in ice, defrost no longer working',
        'Error code, high-pressure or low-pressure cut-out',
        'Unusual noise or vibration from the compressor or fan',
        'Rising electricity use, low refrigerant charge',
      ],
      upkeep: [
        'Cleaning the evaporator and the outdoor unit',
        'Leak check of the refrigeration circuit',
        'Checking pressures, temperatures and the defrost',
        'Checking electrical connections and safety devices',
        'Checking filters and settings to keep efficiency high',
      ],
      setup: [
        'Assessment of heating needs and choice of capacity',
        'Assembly of the outdoor unit and the indoor units',
        'Refrigeration and electrical connections',
        'Commissioning, settings and leak check',
        'A walk-through of the controls and the right settings',
      ],
    },
    fridge: {
      slug: 'commercial-fridge',
      label: 'Fridge',
      name: 'commercial fridge',
      title: 'Commercial fridge, bar fridge and counter fridge',
      your: 'your fridge',
      kw: ['bar fridge', 'counter fridge', 'chest freezer', 'upright fridge', 'freezer'],
      short: 'Commercial fridges, bar fridges, counter fridges, chest freezers and upright cabinets.',
      intro: 'In a kitchen, a bar or a shop, the fridge works without a break. FrigAirco looks after commercial fridges, bar fridges, counter fridges, refrigerated prep tables, chest freezers and upright freezers.',
      faults: [
        'Fridge no longer cooling, or not cooling enough',
        'Bar fridge or counter fridge icing up or leaking water',
        'Noisy compressor, clicking or no longer starting',
        'Faulty thermostat, probe or controller',
        'Fan stopped, worn door seals, chest freezer no longer holding temperature',
      ],
      upkeep: [
        'Dusting and cleaning the condenser',
        'Checking fans, thermostat and probes',
        'Checking and replacing door seals',
        'Cleaning the defrost water drain',
        'Checking temperatures and refrigerant charge',
      ],
      setup: [
        'Advice on the right model: bar fridge, counter fridge, upright cabinet or chest freezer',
        'Delivery, positioning and levelling',
        'Assembly and connection of remote units where needed',
        'Commissioning and temperature set-up',
        'Compliant recovery of the refrigerant from the old unit',
      ],
    },
    display: {
      slug: 'refrigerated-display',
      label: 'Display counter',
      name: 'refrigerated display',
      title: 'Refrigerated display, bakery and butcher counter',
      your: 'your refrigerated display',
      kw: ['bakery counter', 'butcher counter', 'refrigerated counter', 'pastry display case'],
      short: 'Refrigerated displays, bakery counters and butcher counters: your products well presented, at the right temperature.',
      intro: 'A refrigerated display or butcher counter has to keep products cold while showing them off. FrigAirco works on refrigerated displays, bakery and pastry counters, butcher and deli counters and self-service cabinets.',
      faults: [
        'Refrigerated display no longer holding temperature',
        'Misting or condensation on the glass',
        'Butcher counter icing up, evaporator blocked with ice',
        'Water under the counter, condensate tray full',
        'Fan, lighting or controller fault',
      ],
      upkeep: [
        'Cleaning the condenser, the evaporator and the air return grilles',
        'Checking the defrost and the condensate drain',
        'Checking the fans and the air curtain',
        'Checking product display temperatures',
        'Leak check and refrigerant charge check',
      ],
      setup: [
        'Choosing the bakery counter, butcher counter or display case to suit your products',
        'Assembly and positioning in your shop',
        'Connection to a built-in or remote refrigeration unit',
        'Commissioning and temperature set-up',
        'Final check before the products go in',
      ],
    },
    blast: {
      slug: 'blast-chiller',
      label: 'Blast chiller',
      name: 'blast chiller',
      title: 'Blast chiller',
      your: 'your blast chiller',
      kw: ['blast freezer', 'rapid chiller', 'blast chiller-freezer'],
      short: 'Blast chillers and blast freezers to keep the cold chain intact in the kitchen.',
      intro: 'A blast chiller takes your dishes from cooking temperature to chilled in a very short time, as food hygiene rules require. When it stops, the whole kitchen comes to a halt.',
      faults: [
        'Chilling cycle taking too long or never finishing',
        'Target temperature never reached',
        'Faulty core probe, error on the display',
        'Iced-up evaporator, fan stopped',
        'Compressor tripping the breaker or no longer starting',
      ],
      upkeep: [
        'Cleaning the condenser and the evaporator',
        'Checking the core probe and the air probes',
        'Checking door seals and the defrost',
        'Checking pull-down times',
        'Leak check of the refrigeration circuit',
      ],
      setup: [
        'Choosing the capacity to match your production',
        'Positioning and assembly in the kitchen',
        'Electrical connection and water drain',
        'Commissioning and a full test cycle',
        'A walk-through of the chilling and freezing programmes',
      ],
    },
    refrigeration: {
      slug: 'commercial-industrial-refrigeration',
      label: 'Refrigeration',
      name: 'commercial and industrial refrigeration',
      title: 'Commercial and industrial refrigeration',
      your: 'your refrigeration system',
      kw: ['commercial refrigeration', 'industrial refrigeration', 'refrigeration packs', 'condensing units'],
      short: 'Refrigeration systems for supermarkets, food shops, workshops, warehouses and industry.',
      intro: 'Supermarket, cutting plant, logistics warehouse or production site: commercial and industrial refrigeration calls for carefully sized and closely monitored systems. FrigAirco looks after refrigeration packs, condensing units, evaporators and refrigerated cabinets.',
      faults: [
        'Refrigeration pack or condensing unit in fault',
        'Compressor on high-pressure or low-pressure cut-out',
        'Refrigerant leak on the pipework',
        'Evaporator blocked with ice, defrost failure',
        'Fault on the controls, expansion valve or electrical panel',
      ],
      upkeep: [
        'Periodic leak checks required by the F-Gas regulation',
        'Keeping the equipment logbook up to date',
        'Cleaning condensers and evaporators',
        'Checking compressors, oil level and pressures',
        'Checking controls, safety devices and alarms',
      ],
      setup: [
        'Refrigeration design and sizing of the system',
        'Assembly of units, packs, evaporators and pipework',
        'Electrical connection and controls',
        'Leak testing, vacuuming and commissioning',
        'Handover of the documentation and the equipment logbook',
      ],
    },
    chiller: {
      slug: 'chiller',
      label: 'Chiller',
      name: 'chiller',
      title: 'Chiller',
      your: 'your chiller',
      kw: ['water chiller', 'process chiller', 'industrial cooling unit'],
      short: 'Chillers for industrial processes and building air conditioning.',
      intro: 'A chiller supplies the cooling for an industrial process or for the air conditioning of a building. A breakdown can stop a production line: FrigAirco works on air-cooled and water-cooled chillers.',
      faults: [
        'Chiller in high-pressure or low-pressure alarm',
        'Water flow fault: pump or flow switch',
        'Compressor not starting or tripping',
        'Leaving water temperature too high',
        'Refrigerant leak, fouled or frozen heat exchanger',
      ],
      upkeep: [
        'Cleaning condensers and checking heat exchangers',
        'Leak check of the refrigeration circuit',
        'Checking pressures, oil level and current draw',
        'Checking the water circuit: flow, filters, frost protection',
        'Testing safety devices and controls',
      ],
      setup: [
        'Sizing to the cooling capacity required',
        'Positioning and assembly of the chiller',
        'Hydraulic and electrical connections',
        'Commissioning and control set-up',
        'Load testing and handover of operating instructions',
      ],
    },
  },

  zone: {
    title: (z) => fit(62, `Refrigeration engineer ${z.loc}: fridge and AC repair 24/7 | FrigAirco`, `Refrigeration engineer ${z.loc}: fridge repair 24/7 | FrigAirco`, `Refrigeration engineer ${z.loc} | FrigAirco`),
    desc: (z) => `Refrigeration engineer ${z.loc}: cold room repair, air conditioning maintenance, heat pump installation. On call 24 hours a day, 7 days a week.`,
    h1: (z) => `Refrigeration engineer ${z.loc}`,
    sub: 'Cold room, fridge and air conditioning repair, 24/7',
    lead: (z) => `${z.ctx} FrigAirco travels ${z.loc} for the repair, maintenance and installation of your refrigeration and air conditioning equipment, for businesses and homeowners alike.`,
    servicesTitle: (z) => `Our refrigeration and air conditioning services ${z.loc}`,
    nearTitle: (z) => `Places covered around ${z.name}`,
    nearLead: (z) => `We work ${z.loc} and in the neighbouring municipalities:`,
    relatedTitle: 'Nearby areas',
    faq: (z) => [
      [`How quickly can you be on site ${z.loc}?`, `We reply quickly, 24 hours a day, 7 days a week, and arrange the call-out ${z.loc} as soon as possible depending on the urgency.`],
      [`Which equipment do you repair ${z.loc}?`, 'Cold rooms and freezer rooms, freezers, commercial fridges, bar and counter fridges, refrigerated displays, bakery and butcher counters, blast chillers, chillers, air conditioning and heat pumps.'],
      [`Do you also cover the area around ${z.name}?`, `Yes: ${z.near.join(', ')} and the neighbouring municipalities.`],
    ],
  },

  zonesPage: {
    title: 'Refrigeration engineers across Belgium | FrigAirco',
    desc: 'FrigAirco works throughout Belgium: Brussels, Hainaut, Walloon Brabant, Liège, Namur, Luxembourg province, Antwerp, Ghent, Leuven, Mechelen, Hasselt and Kortrijk.',
    h1: 'Refrigeration engineers across Belgium',
    lead: 'Cold room repair, air conditioning maintenance, heat pump installation: choose your region or town.',
  },

  contact: {
    title: 'Contact and quote | FrigAirco refrigeration engineers',
    desc: 'Contact FrigAirco by phone, WhatsApp or form for a fridge or air conditioning repair, a service visit or a quote. Fast response, 24/7.',
    h1: 'Contact and quote request',
    lead: 'For an emergency, call us or message us on WhatsApp: it is the fastest way. For a quote or a question, use the form.',
    formTitle: 'Send us your request',
    phoneLabel: 'Phone',
    phoneNote: 'Emergencies 24/7',
    waLabel: 'WhatsApp',
    waNote: 'Send a photo of the fault',
    mailLabel: 'Email',
    mailNote: 'Quotes and questions',
    areaLabel: 'Area covered',
    areaNote: 'Wallonia, Brussels and Flanders',
  },

  form: {
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    city: 'Postcode and town',
    type: 'Your request',
    types: ['Emergency repair', 'Maintenance or maintenance contract', 'Installation or assembly', 'Quote request', 'Other'],
    equip: 'Equipment concerned',
    equipOther: 'Other',
    message: 'Message',
    messageHint: 'Describe the fault or your project',
    consent: 'I agree to my details being used to answer my request.',
    send: 'Send request',
    sending: 'Sending…',
    ok: 'Thank you, your request has been sent. We will get back to you quickly.',
    error: 'The request could not be sent. Please call us or message us on WhatsApp.',
    mailto: 'Your email program will open with the request ready to send.',
    subject: 'Request via the FrigAirco website',
  },

  blog: {
    title: 'Advice from a refrigeration engineer | FrigAirco',
    desc: 'Practical advice on cold rooms, commercial fridges, air conditioning and heat pumps: common faults, maintenance and good habits.',
    h1: 'Advice from a refrigeration engineer',
    lead: 'Common faults, maintenance and good habits: what you need to know about your refrigeration and air conditioning equipment.',
  },

  articles: [
    {
      key: 'coldroom-not-cooling',
      slug: 'cold-room-not-cooling',
      date: '2026-10-04',
      title: 'Cold room not cooling: what to check before you call',
      desc: 'Cold room not cooling any more? The simple checks to make before calling for cold room repair, and the mistakes to avoid.',
      intro: 'A cold room whose temperature is rising puts your stock at risk. Before calling for cold room repair, a few simple checks can sometimes get the system running again, or at least give the technician the right information.',
      sections: [
        ['1. The door and seals', 'A door that is not properly closed or a damaged seal lets warm, damp air in. Check that the door shuts firmly and that nothing is blocking it.'],
        ['2. The controller and power supply', 'Look at the display: a setpoint changed by mistake, an alarm code, a blank screen? Also check the breaker in the electrical panel.'],
        ['3. Ice on the evaporator', 'An evaporator blocked with ice no longer lets air through. It often points to a defrost fault or a door opened too often. Do not chip the ice off with a tool: you could puncture the coil.'],
        ['4. A dirty condenser', 'Outside the room, the condenser gets rid of the heat. If it is covered in dust or grease, the unit overheats and cuts out.'],
        ['When should you call an engineer?', 'If the compressor will not start, trips the breaker, or the temperature keeps rising, do not keep trying. Keep the door closed, move sensitive products if you can and call for cold room repair: FrigAirco answers 24 hours a day, 7 days a week.'],
      ],
      link: 'combo:depannage:coldroom',
    },
    {
      key: 'aircon-maintenance',
      slug: 'how-often-air-conditioning-maintenance',
      date: '2026-10-04',
      title: 'Air conditioning maintenance: how often and why?',
      desc: 'How often does air conditioning need maintenance? What you can do yourself, what the technician does and what the regulations require.',
      intro: 'Air conditioning that is never serviced cools less well, uses more energy and ends up smelling bad. Here is what you need to know about air conditioning maintenance.',
      sections: [
        ['What you can do yourself', 'Clean the indoor unit filters regularly, every few weeks while the system is in use. Keep the outdoor unit clear too: leaves, dust and objects placed in front of it restrict the airflow.'],
        ['What the technician does', 'Air conditioning maintenance by an engineer goes further: cleaning and disinfecting the indoor unit, cleaning the outdoor coil, checking the condensate drain, and checking the pressures and the tightness of the circuit.'],
        ['How often?', 'For a home, one air conditioning maintenance visit a year is a good baseline. In a shop, restaurant or office where the system runs all day, plan more frequent visits.'],
        ['What about legal requirements?', 'Depending on the quantity of refrigerant in the system, the F-Gas regulation requires periodic leak checks by a certified technician. An air conditioning maintenance contract means you no longer have to think about it.'],
      ],
      link: 'combo:entretien:aircon',
    },
  ],

  legal: {
    title: 'Legal notice | FrigAirco',
    h1: 'Legal notice',
    blocks: (c) => [
      ['Website publisher', `${c.legalName}<br>${c.address}<br>Company number (CBE/VAT): ${c.vat}<br>Phone: ${c.phone}<br>Email: ${c.email}`],
      ['Hosting', c.host],
      ['Intellectual property', 'The text, logo and layout of this website belong to FrigAirco. The brands mentioned belong to their respective owners and are named for information only.'],
      ['Liability', 'The information on this website is given as a guide and does not replace an on-site diagnosis by a technician.'],
    ],
  },

  privacy: {
    title: 'Privacy policy | FrigAirco',
    h1: 'Privacy policy',
    blocks: (c) => [
      ['Data controller', `${c.legalName}, ${c.address}. Contact: ${c.email}.`],
      ['Data collected', 'When you use the contact form, we receive the details you enter: name, phone number, email address, town and message.'],
      ['Use', 'These details are used only to answer your request, prepare a quote and arrange a visit. They are not sold or passed on to third parties.'],
      ['Retention', 'Your details are kept for as long as needed to handle your request and follow up the customer relationship, then deleted.'],
      ['Cookies', 'This website does not use advertising or tracking cookies.'],
      ['Your rights', 'You can ask to access, correct or delete your details by writing to us. You can also lodge a complaint with the Belgian Data Protection Authority (www.dataprotectionauthority.be).'],
    ],
  },
};
