const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

// Garde titres et descriptions dans les longueurs affichées par Google.
const fit = (max, ...opts) => opts.find((o) => o.length <= max) ?? opts.at(-1);
const kwFit = (e, sep, f) => fit(158, ...[3, 2, 1, 0].map((n) => f(n ? sep + e.kw.slice(0, n).join(', ') : '')));

export default {
  code: 'fr',
  hreflang: 'fr-BE',
  ogLocale: 'fr_BE',
  prefix: '',
  label: 'FR',
  langName: 'Français',

  slugs: {
    zones: 'zones',
    zone: 'frigoriste-',
    contact: 'contact',
    blog: 'conseils',
    legal: 'mentions-legales',
    privacy: 'confidentialite',
  },

  t: {
    skip: 'Aller au contenu',
    available: 'Disponible 24h/24 · 7j/7',
    regions: 'Wallonie · Bruxelles · Flandre',
    call: 'Appeler',
    callNumber: (n) => `Appeler le ${n}`,
    quote: 'Demander un devis',
    quoteShort: 'Devis',
    generic: { name: 'frigo ou clim', your: 'votre installation' },
    whatsapp: 'WhatsApp',
    menu: 'Menu',
    subMenu: 'Ouvrir le sous-menu',
    home: 'Accueil',
    zones: 'Zones',
    blog: 'Conseils',
    contact: 'Contact',
    langSwitch: 'Langue',
    learnMore: 'En savoir plus',
    readMore: "Lire l'article",
    allZones: 'Toutes les zones desservies',
    footerTagline: "Frigoriste agréé en Belgique. Dépannage, entretien et installation de froid et de climatisation, 24h/24 et 7j/7.",
    footerServices: 'Services',
    footerZones: 'Zones desservies',
    footerContact: 'Contact',
    legal: 'Mentions légales',
    privacy: 'Confidentialité',
    rights: 'Tous droits réservés.',
    ctaTitle: 'Une panne ou un projet ? Parlons-en.',
    ctaText: 'Appelez-nous, écrivez-nous sur WhatsApp ou envoyez votre demande : nous vous répondons rapidement, à toute heure.',
    zonesTitle: 'Zones desservies',
    zonesLead: 'FrigAirco se déplace dans toute la Belgique : Wallonie, Bruxelles et Flandre.',
    groups: { region: 'Régions', wal: 'Villes de Wallonie', fla: 'Villes de Flandre' },
    faqTitle: 'Questions fréquentes',
    alsoTitle: (e) => `Aussi pour ${e.your}`,
    otherTitle: (a) => `${a.name} : autres équipements`,
    whyTitle: 'Pourquoi choisir FrigAirco',
    why: [
      ['clock', 'Réponse rapide', "Une panne de froid ne peut pas attendre. Nous répondons au téléphone et sur WhatsApp à toute heure et nous organisons l'intervention au plus vite."],
      ['shield', 'Frigoristes agréés', 'Techniciens certifiés F-Gas, entreprise agréée : vos installations sont entre des mains qualifiées et en règle.'],
      ['award', "Plus de 10 ans d'expérience", 'De la chambre froide au chiller, du frigo bar à la pompe à chaleur, nous connaissons les équipements et leurs pannes, toutes marques confondues.'],
      ['users', 'Professionnels et particuliers', 'Horeca, boucheries, boulangeries, commerces alimentaires, industrie et bureaux, mais aussi maisons et appartements.'],
    ],
    certTitle: 'Agréments et marques',
    certLead: "Manipuler des fluides frigorigènes est une activité réglementée. FrigAirco dispose des agréments requis et travaille avec les grandes marques du froid et de la climatisation.",
    certs: {
      'F-Gas': 'Techniciens certifiés pour la manipulation des fluides frigorigènes',
      'Vinçotte': 'Agrément délivré par un organisme de contrôle indépendant',
      'Bruxelles Environnement': 'Entreprise agréée en technique frigorifique',
    },
    brandsTitle: 'Les marques avec lesquelles nous travaillons',
    reviewsTitle: 'Avis clients',
    reviewsLead: 'Ce que nos clients disent de FrigAirco sur Google.',
    reviewsLink: 'Voir tous les avis sur Google',
    sectorsTitle: 'Nos clients',
    sectors: ['Horeca', 'Boucheries', 'Boulangeries-pâtisseries', 'Commerces alimentaires', 'Industrie et logistique', 'Bureaux', 'Particuliers'],
    galleryTitle: 'Nos réalisations',
    toComplete: 'à compléter',
    notFoundTitle: 'Page introuvable',
    notFoundText: "Cette page n'existe pas ou a été déplacée.",
    notFoundBack: "Retour à l'accueil",
  },

  home: {
    title: 'FrigAirco | Frigoriste en Belgique, dépannage 24h/24 et 7j/7',
    desc: 'Frigoriste agréé en Belgique : dépannage chambre froide, entretien climatisation, installation pompe à chaleur. Joignable 24h/24 et 7j/7.',
    badge: 'Frigoriste agréé · Dépannage 24h/24 – 7j/7',
    h1: 'Votre frigoriste en Belgique, <em>24h/24 et 7j/7</em>',
    lead: 'Dépannage chambre froide, entretien climatisation, installation pompe à chaleur, maintenance réfrigération commerciale et industrielle : FrigAirco intervient en Wallonie, à Bruxelles et en Flandre, pour les professionnels et les particuliers.',
    checks: ['Intervention partout en Belgique', 'Professionnels et particuliers', 'Techniciens certifiés F-Gas', 'Toutes marques'],
    stats: [['24h/24', 'Dépannage jour et nuit'], ['7j/7', 'Week-ends et jours fériés'], ['+10 ans', "d'expérience"], ['F-Gas', 'Techniciens certifiés']],
    pickerTitle: 'Quel équipement est en panne ?',
    pickerNote: 'Choisissez votre équipement ou écrivez-nous directement.',
    servicesTitle: 'Nos services de froid et de climatisation',
    servicesLead: 'Trois métiers, un seul interlocuteur pour toutes vos installations de réfrigération et de climatisation.',
    equipTitle: 'Tous vos équipements de froid et de climatisation',
    equipLead: 'Choisissez votre équipement pour voir le détail du dépannage, de l\'entretien et de l\'installation.',
    faq: [
      ['FrigAirco intervient-il vraiment 24h/24 et 7j/7 ?', 'Oui. Le dépannage frigo, chambre froide et climatisation est joignable jour et nuit, week-ends et jours fériés compris.'],
      ['Dans quelles régions intervenez-vous ?', 'En Wallonie, à Bruxelles et en Flandre : Hainaut, Brabant wallon, Liège, Namur, province de Luxembourg, Anvers, Gand, Louvain, Malines, Hasselt, Courtrai et leurs alentours.'],
      ['Sur quels équipements travaillez-vous ?', 'Chambres froides positives et négatives, congélateurs, frigos professionnels, frigos bar et frigos comptoir, comptoirs boulangerie et boucherie, vitrines réfrigérées, bahuts, refroidisseurs rapides, chillers, climatisations et pompes à chaleur.'],
      ['Travaillez-vous aussi pour les particuliers ?', "Oui. Nous assurons l'installation, l'entretien et le dépannage des climatisations et des pompes à chaleur chez les particuliers, en plus du froid commercial et industriel pour les professionnels."],
      ['Vos techniciens sont-ils agréés ?', "Oui. Nos frigoristes sont certifiés F-Gas pour la manipulation des fluides frigorigènes et l'entreprise est agréée en technique frigorifique."],
      ['Comment obtenir un devis ?', 'Remplissez le formulaire de contact, appelez-nous ou écrivez-nous sur WhatsApp en décrivant votre besoin. Nous revenons vers vous rapidement.'],
    ],
  },

  actions: {
    depannage: {
      slug: 'depannage',
      nav: 'Dépannage',
      name: 'Dépannage',
      listKey: 'faults',
      hub: {
        title: 'Dépannage frigo et chambre froide 24h/24 7j/7 | FrigAirco',
        desc: 'Dépannage chambre froide, frigo, climatisation, pompe à chaleur, vitrine réfrigérée et chiller. Frigoristes agréés joignables 24h/24 et 7j/7 partout en Belgique.',
        h1: 'Dépannage frigo, chambre froide et climatisation 24h/24 – 7j/7',
        cardTitle: 'Dépannage frigo et clim 24h/24',
        lead: "Une panne de froid n'attend pas. FrigAirco assure le dépannage de vos installations de réfrigération et de climatisation de jour comme de nuit, week-ends et jours fériés compris, partout en Belgique.",
        card: 'Chambre froide à l\'arrêt, frigo qui ne refroidit plus, clim en panne : un frigoriste joignable jour et nuit.',
      },
      pair: (e) => `Dépannage ${e.name}`,
      title: (e) => fit(62, `Dépannage ${e.name} 24h/24 7j/7 en Belgique | FrigAirco`, `Dépannage ${e.name} 24h/24 7j/7 | FrigAirco`, `Dépannage ${e.name} 24h/24 | FrigAirco`),
      desc: (e) => kwFit(e, ' : ', (k) => `Dépannage ${e.name} 24h/24 et 7j/7 partout en Belgique${k}. Frigoristes agréés, réponse rapide.`),
      h1: (e) => `Dépannage ${e.name} 24h/24 et 7j/7`,
      lead: (e) => `${cap(e.your)} est en panne ? Nos frigoristes interviennent 24h/24 et 7j/7 en Wallonie, à Bruxelles et en Flandre pour le dépannage ${e.name} : diagnostic sur place, réparation et remise en service.`,
      listTitle: (e) => `Dépannage ${e.name} : les pannes les plus fréquentes`,
      stepsTitle: (e) => `Comment se déroule un dépannage ${e.name} ?`,
      steps: [
        ['Vous appelez ou écrivez sur WhatsApp', 'Décrivez la panne : nous vous répondons rapidement, à toute heure.'],
        ['Diagnostic sur place', "Le technicien identifie l'origine de la panne et vous explique ce qu'il faut faire."],
        ['Réparation', 'Remplacement de la pièce en cause, réparation de la fuite, recharge en fluide si nécessaire.'],
        ['Remise en service', 'Contrôle des températures et conseils pour éviter que la panne ne revienne.'],
      ],
      faq: (e) => [
        [`Intervenez-vous la nuit et le week-end pour un dépannage ${e.name} ?`, `Oui. Le dépannage ${e.name} est assuré 24h/24 et 7j/7, jours fériés compris. Appelez-nous ou envoyez un message WhatsApp.`],
        [`Dans quelles régions assurez-vous le dépannage ${e.name} ?`, 'Partout en Belgique : en Wallonie, à Bruxelles et en Flandre.'],
        ['Que faire en attendant le technicien ?', "Notez le code d'erreur ou la température affichée, évitez de relancer l'appareil plusieurs fois de suite et, s'il s'agit de froid alimentaire, gardez les portes fermées pour conserver le froid."],
      ],
    },
    entretien: {
      slug: 'entretien-maintenance',
      nav: 'Entretien',
      name: 'Entretien et maintenance',
      listKey: 'upkeep',
      hub: {
        title: 'Entretien et maintenance frigo et clim | FrigAirco',
        desc: 'Entretien climatisation, maintenance chambre froide, entretien pompe à chaleur. Visite ponctuelle ou contrat de maintenance, partout en Belgique.',
        h1: 'Entretien et maintenance frigo, chambre froide et climatisation',
        cardTitle: 'Entretien et maintenance frigo et clim',
        lead: "Un entretien régulier évite la plupart des pannes, réduit la consommation et prolonge la vie de vos appareils. FrigAirco assure l'entretien ponctuel et la maintenance sous contrat de vos installations de froid et de climatisation.",
        card: 'Visites ponctuelles ou contrat de maintenance : moins de pannes, moins de consommation, des contrôles en règle.',
      },
      pair: (e) => `Entretien ${e.name}`,
      title: (e) => fit(62, `Entretien et maintenance ${e.name} en Belgique | FrigAirco`, `Entretien et maintenance ${e.name} | FrigAirco`),
      desc: (e) => kwFit(e, ' : ', (k) => `Entretien et maintenance ${e.name} par des frigoristes agréés${k}. Visite ponctuelle ou contrat, partout en Belgique.`),
      h1: (e) => `Entretien et maintenance ${e.name}`,
      lead: (e) => `Un entretien ${e.name} régulier, c'est moins de pannes, une consommation maîtrisée et un appareil qui dure. FrigAirco assure l'entretien ponctuel et la maintenance ${e.name} sous contrat, pour les professionnels et les particuliers.`,
      listTitle: (e) => `Ce que comprend l'entretien ${e.name}`,
      extra: (e) => [`Maintenance ${e.name} : le contrat`, `Avec un contrat de maintenance ${e.name}, les visites sont planifiées à l'avance et les contrôles consignés à chaque passage. La fréquence est fixée avec vous selon l'appareil et son usage.`],
      stepsTitle: (e) => `Comment se passe l'entretien ${e.name} ?`,
      steps: [
        ['Prise de rendez-vous', 'Nous fixons une date qui gêne le moins possible votre activité.'],
        ['Visite du technicien', 'Nettoyage, contrôles et réglages selon la liste propre à votre appareil.'],
        ['Compte rendu', "Vous savez ce qui a été fait et ce qu'il faudra surveiller."],
        ['Suivi', 'Sous contrat, la visite suivante est déjà planifiée.'],
      ],
      faq: (e) => [
        [`À quelle fréquence prévoir l'entretien ${e.name} ?`, "Cela dépend de l'appareil et de son usage. Un passage par an est un minimum courant ; les installations qui tournent en continu, ou dans un milieu gras ou poussiéreux, demandent des visites plus rapprochées. Nous fixons la fréquence avec vous."],
        [`L'entretien ${e.name} est-il obligatoire ?`, "Au-delà d'une certaine quantité de fluide frigorigène, la réglementation F-Gas impose des contrôles d'étanchéité périodiques réalisés par un technicien certifié. Nous vous disons ce qui s'applique à votre installation."],
        [`Proposez-vous un contrat de maintenance ${e.name} ?`, `Oui. Le contrat de maintenance ${e.name} prévoit des visites planifiées et un suivi de l'installation. Demandez un devis.`],
      ],
    },
    installation: {
      slug: 'installation-montage',
      nav: 'Installation',
      name: 'Installation et montage',
      listKey: 'setup',
      hub: {
        title: 'Installation et montage chambre froide et clim | FrigAirco',
        desc: 'Installation chambre froide, montage climatisation, installation pompe à chaleur et chiller. Étude et mise en service par des frigoristes agréés.',
        h1: 'Installation et montage chambre froide, climatisation et pompe à chaleur',
        cardTitle: 'Installation et montage frigo et clim',
        lead: "Une installation bien dimensionnée et bien montée consomme moins et tombe moins en panne. FrigAirco étudie votre besoin, fournit le matériel et assure le montage et la mise en service.",
        card: 'Étude, fourniture, montage et mise en service de vos équipements de froid et de climatisation.',
      },
      pair: (e) => `Installation ${e.name}`,
      title: (e) => fit(62, `Installation et montage ${e.name} en Belgique | FrigAirco`, `Installation et montage ${e.name} | FrigAirco`),
      desc: (e) => kwFit(e, ' : ', (k) => `Installation et montage ${e.name} par des frigoristes agréés${k}. Étude, devis et mise en service partout en Belgique.`),
      h1: (e) => `Installation et montage ${e.name}`,
      lead: (e) => `Nouveau projet ou remplacement d'un appareil en fin de vie : FrigAirco prend en charge l'installation ${e.name} de l'étude à la mise en service, avec un montage ${e.name} soigné réalisé par des frigoristes agréés.`,
      listTitle: (e) => `Installation ${e.name} : les étapes`,
      stepsTitle: (e) => `Votre projet de montage ${e.name}, pas à pas`,
      steps: [
        ['Visite et étude', 'Nous regardons les lieux, vos contraintes et ce dont vous avez réellement besoin.'],
        ['Devis', 'Un devis clair, avec le matériel proposé et les travaux prévus.'],
        ['Pose et raccordements', 'Mise en place, raccordements et finitions par nos techniciens.'],
        ['Mise en service', "Essais, réglages et explication de l'utilisation."],
      ],
      faq: (e) => [
        [`Combien coûte une installation ${e.name} ?`, 'Le prix dépend de la puissance, du matériel choisi et de la configuration des lieux. Nous établissons un devis après avoir étudié votre besoin.'],
        ['Quelles marques installez-vous ?', "Nous travaillons notamment avec Daikin, Mitsubishi Electric, Fujitsu, Bitzer et Danfoss, et nous assurons aussi l'entretien et le dépannage des autres marques."],
        [`Assurez-vous l'entretien après le montage ${e.name} ?`, `Oui. Après l'installation, nous pouvons assurer l'entretien et la maintenance ${e.name}, ainsi que le dépannage 24h/24 et 7j/7.`],
      ],
    },
  },

  equipment: {
    coldroom: {
      slug: 'chambre-froide',
      label: 'Chambre froide',
      name: 'chambre froide',
      title: 'Chambre froide',
      your: 'votre chambre froide',
      kw: ['chambre froide positive', 'chambre négative', 'congélateur', 'chambre de congélation'],
      short: "Chambres froides positives et négatives, congélateurs et chambres de congélation pour l'horeca, les commerces et l'industrie.",
      intro: "Une chambre froide qui s'arrête, ce sont des marchandises en danger en quelques heures. FrigAirco s'occupe des chambres froides positives (0 à +8 °C), des chambres négatives et des congélateurs (jusqu'à −25 °C), quels que soient la marque et le volume.",
      faults: [
        'Chambre froide qui ne descend plus en température ou dont la température est instable',
        'Chambre négative ou congélateur qui givre : évaporateur pris en glace, dégivrage en défaut',
        'Compresseur qui ne démarre plus, disjoncte ou tourne sans arrêt',
        'Fuite de fluide frigorigène, manque de gaz',
        'Porte, joints ou charnières qui ne ferment plus, alarme de température',
      ],
      upkeep: [
        "Nettoyage du condenseur et de l'évaporateur",
        "Contrôle d'étanchéité du circuit et des pressions de fonctionnement",
        "Vérification du dégivrage, des ventilateurs et de l'écoulement des condensats",
        'Contrôle des joints de porte, des charnières et des résistances de cadre en chambre négative',
        'Relevé des températures et réglage du régulateur',
      ],
      setup: [
        'Étude du volume, des températures et des produits à stocker',
        'Montage des panneaux isolants, de la porte et du sol',
        "Installation du groupe frigorifique et de l'évaporateur",
        'Raccordement, tirage au vide, charge en fluide et mise en service',
        "Réglage du régulateur et explication de l'utilisation",
      ],
    },
    aircon: {
      slug: 'climatisation',
      label: 'Climatisation',
      name: 'climatisation',
      title: 'Climatisation, clim et airco',
      your: 'votre climatisation',
      kw: ['clim', 'airco', 'climatiseur', 'split et multisplit'],
      short: 'Clim, airco et climatisation réversible pour maisons, bureaux, commerces et horeca.',
      intro: "Clim, airco, climatisation : peu importe le nom, FrigAirco s'occupe de vos climatiseurs muraux, consoles, cassettes et gainables, en monosplit comme en multisplit, chez les particuliers et les professionnels.",
      faults: [
        'Clim qui ne refroidit plus ou ne chauffe plus',
        "Airco qui coule : fuite d'eau à l'unité intérieure, condensats bouchés",
        'Code erreur affiché, voyant qui clignote, télécommande sans effet',
        'Mauvaises odeurs ou bruit anormal',
        'Unité extérieure qui ne démarre pas, manque de fluide frigorigène',
      ],
      upkeep: [
        "Nettoyage et désinfection des filtres et de l'unité intérieure",
        "Nettoyage de l'échangeur de l'unité extérieure",
        "Contrôle d'étanchéité et des pressions du circuit",
        "Vérification de l'évacuation des condensats",
        'Test des modes froid et chaud, contrôle des températures de soufflage',
      ],
      setup: [
        'Visite et conseil : puissance, emplacement des unités, monosplit ou multisplit',
        'Montage des unités intérieure et extérieure',
        'Liaisons frigorifiques, évacuation des condensats et alimentation électrique',
        "Tirage au vide, mise en service et contrôle d'étanchéité",
        'Explication de la télécommande et des réglages',
      ],
    },
    heatpump: {
      slug: 'pompe-a-chaleur',
      label: 'Pompe à chaleur',
      name: 'pompe à chaleur',
      title: 'Pompe à chaleur',
      your: 'votre pompe à chaleur',
      kw: ['pompe à chaleur air-air', 'pompe à chaleur air-eau', 'PAC réversible'],
      short: 'Pompes à chaleur air-air et air-eau pour chauffer et rafraîchir en consommant moins.',
      intro: "Une pompe à chaleur fonctionne sur un circuit frigorifique : c'est un métier de frigoriste. FrigAirco intervient sur les pompes à chaleur air-air et air-eau, pour le chauffage, le rafraîchissement et l'eau chaude.",
      faults: [
        'Pompe à chaleur qui ne chauffe plus ou chauffe mal',
        'Unité extérieure prise en glace, dégivrage qui ne se fait plus',
        'Code erreur, mise en sécurité haute ou basse pression',
        'Bruit ou vibrations anormales du compresseur ou du ventilateur',
        'Consommation électrique qui grimpe, manque de fluide frigorigène',
      ],
      upkeep: [
        "Nettoyage de l'évaporateur et de l'unité extérieure",
        "Contrôle d'étanchéité du circuit frigorifique",
        'Vérification des pressions, des températures et du dégivrage',
        'Contrôle des raccordements électriques et des sécurités',
        'Vérification des filtres et des réglages pour garder un bon rendement',
      ],
      setup: [
        'Étude des besoins de chauffage et choix de la puissance',
        "Montage de l'unité extérieure et des unités intérieures",
        'Raccordements frigorifiques et électriques',
        "Mise en service, réglages et contrôle d'étanchéité",
        'Explication de la régulation et des bons réglages',
      ],
    },
    fridge: {
      slug: 'frigo-professionnel',
      label: 'Frigo',
      name: 'frigo',
      title: 'Frigo, frigo bar et frigo comptoir',
      your: 'votre frigo',
      kw: ['frigo bar', 'frigo comptoir', 'bahut', 'armoire réfrigérée', 'congélateur'],
      short: 'Frigos professionnels, frigos bar, frigos comptoir, bahuts et armoires réfrigérées.',
      intro: "Dans une cuisine, un bar ou un commerce, le frigo travaille sans interruption. FrigAirco s'occupe des frigos professionnels, frigos bar, frigos comptoir, tables réfrigérées, bahuts et armoires de congélation.",
      faults: [
        'Frigo qui ne refroidit plus ou trop peu',
        "Frigo bar ou frigo comptoir qui fait du givre ou de l'eau",
        'Compresseur bruyant, qui claque ou ne démarre plus',
        'Thermostat, sonde ou régulateur en défaut',
        "Ventilateur à l'arrêt, joints de porte usés, bahut qui ne tient plus sa température",
      ],
      upkeep: [
        'Dépoussiérage et nettoyage du condenseur',
        'Contrôle des ventilateurs, du thermostat et des sondes',
        'Vérification et remplacement des joints de porte',
        "Nettoyage de l'évacuation des eaux de dégivrage",
        'Contrôle des températures et de la charge en fluide',
      ],
      setup: [
        'Conseil sur le modèle adapté : frigo bar, frigo comptoir, armoire ou bahut',
        'Livraison, mise en place et mise à niveau',
        'Montage et raccordement des groupes à distance si nécessaire',
        'Mise en service et réglage des températures',
        "Récupération du fluide frigorigène de l'ancien appareil dans les règles",
      ],
    },
    display: {
      slug: 'vitrine-refrigeree',
      label: 'Vitrine et comptoir',
      name: 'vitrine réfrigérée',
      title: 'Vitrine réfrigérée, comptoir boulangerie et boucherie',
      your: 'votre vitrine réfrigérée',
      kw: ['comptoir boulangerie', 'comptoir boucherie', 'comptoir réfrigéré', 'vitrine pâtisserie'],
      short: 'Vitrines réfrigérées, comptoirs boulangerie et comptoirs boucherie : vos produits bien exposés, à la bonne température.',
      intro: "Une vitrine réfrigérée ou un comptoir boucherie doit garder les produits au froid tout en les mettant en valeur. FrigAirco intervient sur les vitrines réfrigérées, comptoirs boulangerie-pâtisserie, comptoirs boucherie-charcuterie et meubles de libre-service.",
      faults: [
        'Vitrine réfrigérée qui ne tient plus sa température',
        'Buée ou condensation sur les vitres',
        'Comptoir boucherie qui givre, évaporateur bloqué par la glace',
        'Eau qui coule sous le comptoir, bac de condensats plein',
        'Ventilation, éclairage ou régulateur en panne',
      ],
      upkeep: [
        "Nettoyage du condenseur, de l'évaporateur et des grilles de reprise d'air",
        "Contrôle du dégivrage et de l'évacuation des condensats",
        "Vérification des ventilateurs et du rideau d'air",
        "Contrôle des températures d'exposition des produits",
        "Contrôle d'étanchéité et de la charge en fluide",
      ],
      setup: [
        'Choix du comptoir boulangerie, du comptoir boucherie ou de la vitrine selon vos produits',
        'Montage et mise en place dans votre magasin',
        'Raccordement à un groupe logé ou à un groupe à distance',
        'Mise en service et réglage des températures',
        'Contrôle final avant le chargement des produits',
      ],
    },
    blast: {
      slug: 'refroidisseur-rapide',
      label: 'Refroidisseur rapide',
      name: 'refroidisseur rapide',
      title: 'Refroidisseur rapide',
      your: 'votre refroidisseur rapide',
      kw: ['cellule de refroidissement rapide', 'surgélateur rapide', 'cellule mixte'],
      short: 'Refroidisseurs rapides et cellules de surgélation pour respecter la chaîne du froid en cuisine.',
      intro: "Le refroidisseur rapide fait passer vos préparations de la cuisson au froid en un temps très court, pour respecter les règles d'hygiène alimentaire. Quand il s'arrête, c'est toute la production de la cuisine qui est bloquée.",
      faults: [
        'Cycle de refroidissement trop long ou qui ne se termine pas',
        'Température cible jamais atteinte',
        "Sonde à cœur défectueuse, erreur à l'afficheur",
        "Évaporateur givré, ventilateur à l'arrêt",
        'Compresseur qui disjoncte ou ne démarre plus',
      ],
      upkeep: [
        "Nettoyage du condenseur et de l'évaporateur",
        "Contrôle de la sonde à cœur et des sondes d'ambiance",
        'Vérification des joints de porte et du dégivrage',
        'Contrôle des temps de descente en température',
        "Contrôle d'étanchéité du circuit frigorifique",
      ],
      setup: [
        'Choix de la capacité selon votre production',
        'Mise en place et montage dans la cuisine',
        'Raccordement électrique et évacuation des eaux',
        "Mise en service et test d'un cycle complet",
        'Explication des programmes de refroidissement et de surgélation',
      ],
    },
    refrigeration: {
      slug: 'refrigeration-commerciale-industrielle',
      label: 'Réfrigération',
      name: 'réfrigération commerciale et industrielle',
      title: 'Réfrigération commerciale et industrielle',
      your: 'votre installation de réfrigération',
      kw: ['réfrigération commerciale', 'réfrigération industrielle', 'centrale frigorifique', 'groupe de condensation'],
      short: 'Installations de réfrigération pour supermarchés, commerces alimentaires, ateliers, entrepôts et industrie.',
      intro: "Supermarché, atelier de découpe, entrepôt logistique ou site de production : la réfrigération commerciale et industrielle demande des installations dimensionnées avec soin et suivies de près. FrigAirco s'occupe des centrales frigorifiques, groupes de condensation, évaporateurs et meubles froids.",
      faults: [
        'Centrale frigorifique ou groupe de condensation en défaut',
        'Compresseur en sécurité haute pression ou basse pression',
        'Fuite de fluide frigorigène sur le réseau',
        'Évaporateur pris en glace, dégivrage en panne',
        'Régulation, détendeur ou armoire électrique en défaut',
      ],
      upkeep: [
        "Contrôles d'étanchéité périodiques prévus par la réglementation F-Gas",
        "Tenue du registre de l'installation",
        'Nettoyage des condenseurs et des évaporateurs',
        "Contrôle des compresseurs, du niveau d'huile et des pressions",
        'Vérification de la régulation, des sécurités et des alarmes',
      ],
      setup: [
        "Étude frigorifique et dimensionnement de l'installation",
        'Montage des groupes, centrales, évaporateurs et tuyauteries',
        'Raccordement électrique et régulation',
        "Essais d'étanchéité, tirage au vide et mise en service",
        "Remise du dossier et du registre de l'installation",
      ],
    },
    chiller: {
      slug: 'chiller',
      label: 'Chiller',
      name: 'chiller',
      title: "Chiller et groupe d'eau glacée",
      your: 'votre chiller',
      kw: ["groupe d'eau glacée", 'refroidisseur de liquide', 'groupe froid industriel'],
      short: "Chillers et groupes d'eau glacée pour les process industriels et la climatisation des bâtiments.",
      intro: "Le chiller, ou groupe d'eau glacée, produit le froid d'un process industriel ou de la climatisation d'un bâtiment. Une panne peut arrêter une ligne de production : FrigAirco intervient sur les chillers à condensation par air ou par eau.",
      faults: [
        'Chiller en alarme haute pression ou basse pression',
        "Défaut de débit d'eau : pompe ou contrôleur de débit en cause",
        'Compresseur qui ne démarre pas ou déclenche',
        "Température de sortie d'eau trop élevée",
        'Fuite de fluide frigorigène, échangeur encrassé ou gelé',
      ],
      upkeep: [
        'Nettoyage des condenseurs et contrôle des échangeurs',
        "Contrôle d'étanchéité du circuit frigorifique",
        "Vérification des pressions, du niveau d'huile et des intensités",
        "Contrôle du circuit d'eau : débit, filtres, protection antigel",
        'Test des sécurités et de la régulation',
      ],
      setup: [
        'Dimensionnement selon la puissance frigorifique nécessaire',
        'Mise en place et montage du chiller',
        'Raccordements hydrauliques et électriques',
        'Mise en service et réglage de la régulation',
        "Essais en charge et remise des consignes d'exploitation",
      ],
    },
  },

  zone: {
    title: (z) => fit(62, `Frigoriste ${z.loc} : dépannage frigo et clim 24h/24 | FrigAirco`, `Frigoriste ${z.loc} : dépannage frigo 24h/24 | FrigAirco`, `Frigoriste ${z.loc} 24h/24 et 7j/7 | FrigAirco`),
    desc: (z) => `Frigoriste ${z.loc} : dépannage chambre froide, entretien climatisation, installation pompe à chaleur. Joignable 24h/24 et 7j/7.`,
    h1: (z) => `Frigoriste ${z.loc}`,
    sub: 'Dépannage chambre froide, frigo et climatisation 24h/24 – 7j/7',
    lead: (z) => `${z.ctx} FrigAirco se déplace ${z.loc} pour le dépannage, l'entretien et l'installation de vos équipements de froid et de climatisation, chez les professionnels comme chez les particuliers.`,
    servicesTitle: (z) => `Nos services de froid et de climatisation ${z.loc}`,
    nearTitle: (z) => `Communes desservies autour de ${z.name}`,
    nearLead: (z) => `Nous intervenons ${z.loc} et dans les communes voisines :`,
    relatedTitle: 'Zones voisines',
    faq: (z) => [
      [`Quel est le délai d'intervention ${z.loc} ?`, `Nous répondons rapidement, 24h/24 et 7j/7, et nous organisons le déplacement ${z.loc} au plus vite selon l'urgence.`],
      [`Quels équipements dépannez-vous ${z.loc} ?`, 'Chambres froides positives et négatives, congélateurs, frigos professionnels, frigos bar et comptoir, vitrines réfrigérées, comptoirs boulangerie et boucherie, refroidisseurs rapides, chillers, climatisations et pompes à chaleur.'],
      [`Intervenez-vous aussi autour de ${z.name} ?`, `Oui : ${z.near.join(', ')} et les communes voisines.`],
    ],
  },

  zonesPage: {
    title: 'Frigoriste en Wallonie, à Bruxelles et en Flandre | FrigAirco',
    desc: 'FrigAirco intervient partout en Belgique : Bruxelles, Hainaut, Brabant wallon, Liège, Namur, Luxembourg, Anvers, Gand, Louvain, Malines et Hasselt.',
    h1: 'Frigoriste partout en Belgique',
    lead: 'Dépannage chambre froide, entretien climatisation, installation pompe à chaleur : choisissez votre région ou votre ville.',
  },

  contact: {
    title: 'Contact et devis | FrigAirco, frigoriste 24h/24 et 7j/7',
    desc: 'Contactez FrigAirco par téléphone, WhatsApp ou formulaire pour un dépannage frigo ou clim, un entretien ou un devis. Réponse rapide, 24h/24 et 7j/7.',
    h1: 'Contact et demande de devis',
    lead: 'Pour une urgence, appelez-nous ou écrivez-nous sur WhatsApp : c\'est le plus rapide. Pour un devis ou une question, utilisez le formulaire.',
    formTitle: 'Envoyez-nous votre demande',
    phoneLabel: 'Téléphone',
    phoneNote: 'Urgences 24h/24 – 7j/7',
    waLabel: 'WhatsApp',
    waNote: 'Envoyez une photo de la panne',
    mailLabel: 'E-mail',
    mailNote: 'Devis et questions',
    areaLabel: 'Zone desservie',
    areaNote: 'Wallonie, Bruxelles et Flandre',
  },

  form: {
    name: 'Nom',
    phone: 'Téléphone',
    email: 'E-mail',
    city: 'Code postal et localité',
    type: 'Votre demande',
    types: ['Dépannage urgent', 'Entretien ou contrat de maintenance', 'Installation ou montage', 'Demande de devis', 'Autre'],
    equip: 'Équipement concerné',
    equipOther: 'Autre',
    message: 'Message',
    messageHint: 'Décrivez la panne ou votre projet',
    consent: "J'accepte que mes données soient utilisées pour répondre à ma demande.",
    send: 'Envoyer la demande',
    sending: 'Envoi en cours…',
    ok: 'Merci, votre demande est bien partie. Nous revenons vers vous rapidement.',
    error: "L'envoi n'a pas abouti. Appelez-nous ou écrivez-nous sur WhatsApp.",
    mailto: 'Votre logiciel de messagerie va s\'ouvrir avec la demande prête à envoyer.',
    subject: 'Demande via le site FrigAirco',
  },

  blog: {
    title: 'Conseils de frigoriste : froid et climatisation | FrigAirco',
    desc: 'Conseils pratiques sur la chambre froide, le frigo professionnel, la climatisation et la pompe à chaleur : pannes courantes, entretien, bons réflexes.',
    h1: 'Conseils de frigoriste',
    lead: 'Pannes courantes, entretien, bons réflexes : ce qu\'il faut savoir sur vos équipements de froid et de climatisation.',
  },

  articles: [
    {
      key: 'coldroom-not-cooling',
      slug: 'chambre-froide-ne-refroidit-plus',
      date: '2026-10-04',
      title: "Chambre froide qui ne refroidit plus : que vérifier avant d'appeler",
      desc: "Votre chambre froide ne refroidit plus ? Les vérifications simples à faire avant d'appeler le dépannage chambre froide, et les erreurs à éviter.",
      intro: "Une chambre froide dont la température remonte, c'est du stock en danger. Avant d'appeler le dépannage chambre froide, quelques vérifications simples permettent parfois de relancer l'installation, ou au moins de donner les bonnes informations au technicien.",
      sections: [
        ['1. La porte et les joints', "Une porte mal fermée ou un joint abîmé laissent entrer l'air chaud et humide. Vérifiez que la porte se ferme franchement et que rien ne la bloque."],
        ["2. Le régulateur et l'alimentation", "Regardez l'afficheur : consigne modifiée par erreur, code d'alarme, écran éteint ? Contrôlez aussi le disjoncteur dans le tableau électrique."],
        ["3. Le givre sur l'évaporateur", "Un évaporateur pris dans la glace ne laisse plus passer l'air. C'est souvent le signe d'un dégivrage en panne ou d'une porte trop souvent ouverte. Ne cassez pas la glace avec un outil : vous risquez de percer l'échangeur."],
        ['4. Le condenseur encrassé', "À l'extérieur de la chambre, le condenseur évacue la chaleur. S'il est couvert de poussière ou de graisse, le groupe surchauffe et se met en sécurité."],
        ['Quand appeler un frigoriste ?', "Si le compresseur ne démarre pas, disjoncte, ou si la température continue de monter, n'insistez pas. Gardez la porte fermée, déplacez les produits sensibles si possible et appelez le dépannage chambre froide : FrigAirco répond 24h/24 et 7j/7."],
      ],
      link: 'combo:depannage:coldroom',
    },
    {
      key: 'aircon-maintenance',
      slug: 'frequence-entretien-climatisation',
      date: '2026-10-04',
      title: 'Entretien climatisation : à quelle fréquence et pourquoi ?',
      desc: "À quelle fréquence faire l'entretien climatisation ? Ce que vous pouvez faire vous-même, ce que fait le technicien et ce que prévoit la réglementation.",
      intro: "Une clim qui n'est jamais entretenue refroidit moins bien, consomme plus et finit par sentir mauvais. Voici ce qu'il faut savoir sur l'entretien climatisation.",
      sections: [
        ['Ce que vous pouvez faire vous-même', "Nettoyez les filtres de l'unité intérieure régulièrement, toutes les quelques semaines en période d'utilisation. Dégagez aussi l'unité extérieure : feuilles, poussières et objets posés devant gênent le passage de l'air."],
        ['Ce que fait le technicien', "L'entretien airco par un frigoriste va plus loin : nettoyage et désinfection de l'unité intérieure, nettoyage de l'échangeur extérieur, contrôle de l'évacuation des condensats, vérification des pressions et de l'étanchéité du circuit."],
        ['À quelle fréquence ?', 'Pour une habitation, un entretien climatisation par an est une bonne base. Dans un commerce, un restaurant ou un bureau où la clim tourne toute la journée, prévoyez des passages plus rapprochés.'],
        ['Et les obligations ?', "Selon la quantité de fluide frigorigène de l'installation, la réglementation F-Gas impose des contrôles d'étanchéité périodiques par un technicien certifié. Un contrat de maintenance climatisation permet de ne plus avoir à y penser."],
      ],
      link: 'combo:entretien:aircon',
    },
  ],

  legal: {
    title: 'Mentions légales | FrigAirco',
    h1: 'Mentions légales',
    blocks: (c) => [
      ['Éditeur du site', `${c.legalName}<br>${c.address}<br>Numéro d'entreprise (BCE/TVA) : ${c.vat}<br>Téléphone : ${c.phone}<br>E-mail : ${c.email}`],
      ['Hébergement', c.host],
      ['Propriété intellectuelle', "Les textes, le logo et la mise en page de ce site appartiennent à FrigAirco. Les marques citées appartiennent à leurs propriétaires respectifs et sont mentionnées à titre d'information."],
      ['Responsabilité', "Les informations publiées sur ce site sont données à titre indicatif et ne remplacent pas le diagnostic d'un technicien sur place."],
    ],
  },

  privacy: {
    title: 'Politique de confidentialité | FrigAirco',
    h1: 'Politique de confidentialité',
    blocks: (c) => [
      ['Responsable du traitement', `${c.legalName}, ${c.address}. Contact : ${c.email}.`],
      ['Données collectées', 'Lorsque vous utilisez le formulaire de contact, nous recevons les informations que vous y indiquez : nom, téléphone, adresse e-mail, localité et message.'],
      ['Utilisation', 'Ces données servent uniquement à répondre à votre demande, à établir un devis et à organiser une intervention. Elles ne sont ni vendues ni cédées à des tiers.'],
      ['Durée de conservation', 'Vos données sont conservées le temps nécessaire au traitement de votre demande et au suivi de la relation commerciale, puis supprimées.'],
      ['Cookies', "Ce site n'utilise pas de cookies publicitaires ni de cookies de suivi."],
      ['Vos droits', "Vous pouvez demander l'accès à vos données, leur rectification ou leur suppression en nous écrivant. Vous pouvez aussi introduire une réclamation auprès de l'Autorité de protection des données (www.autoriteprotectiondonnees.be)."],
    ],
  },
};
