const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

// Garde titres et descriptions dans les longueurs affichées par Google.
const fit = (max, ...opts) => opts.find((o) => o.length <= max) ?? opts.at(-1);
const kwFit = (e, sep, f) => fit(158, ...[3, 2, 1, 0].map((n) => f(n ? sep + e.kw.slice(0, n).join(', ') : '')));

export default {
  code: 'nl',
  hreflang: 'nl-BE',
  ogLocale: 'nl_BE',
  prefix: '/nl',
  label: 'NL',
  langName: 'Nederlands',

  slugs: {
    zones: 'regios',
    zone: 'koeltechnicus-',
    contact: 'contact',
    blog: 'advies',
    legal: 'wettelijke-vermeldingen',
    privacy: 'privacy',
  },

  t: {
    skip: 'Naar de inhoud',
    available: 'Bereikbaar 24/7',
    regions: 'Vlaanderen · Brussel · Wallonië',
    call: 'Bellen',
    callNumber: (n) => `Bel ${n}`,
    quote: 'Offerte aanvragen',
    quoteShort: 'Offerte',
    generic: { name: 'koeling of airco', your: 'uw installatie' },
    whatsapp: 'WhatsApp',
    menu: 'Menu',
    subMenu: 'Submenu openen',
    home: 'Home',
    zones: "Regio's",
    blog: 'Advies',
    contact: 'Contact',
    langSwitch: 'Taal',
    learnMore: 'Meer info',
    readMore: 'Artikel lezen',
    allZones: "Alle regio's",
    footerTagline: 'Erkend koeltechnicus in België. Herstelling, onderhoud en installatie van koeling en airco, 24 uur per dag en 7 dagen per week.',
    footerServices: 'Diensten',
    footerZones: "Regio's",
    footerContact: 'Contact',
    legal: 'Wettelijke vermeldingen',
    privacy: 'Privacy',
    rights: 'Alle rechten voorbehouden.',
    ctaTitle: 'Een panne of een project? Laat het ons weten.',
    ctaText: 'Bel ons, stuur een WhatsApp-bericht of verzend uw aanvraag: wij antwoorden snel, op elk uur.',
    zonesTitle: "Regio's waar wij werken",
    zonesLead: 'FrigAirco komt langs in heel België: Vlaanderen, Brussel en Wallonië.',
    groups: { region: 'Gewesten', wal: 'Steden in Wallonië', fla: 'Steden in Vlaanderen' },
    faqTitle: 'Veelgestelde vragen',
    alsoTitle: (e) => `Ook voor ${e.your}`,
    otherTitle: (a) => `${a.name}: andere toestellen`,
    whyTitle: 'Waarom FrigAirco',
    why: [
      ['clock', 'Snel antwoord', 'Een koelpanne kan niet wachten. Wij zijn op elk uur bereikbaar per telefoon en WhatsApp en plannen de interventie zo snel mogelijk.'],
      ['shield', 'Erkende koeltechnici', 'F-gassen-gecertificeerde technici en een erkend bedrijf: uw installaties zijn in bekwame handen en in orde met de regelgeving.'],
      ['award', 'Meer dan 10 jaar ervaring', 'Van koelcel tot chiller, van barkoelkast tot warmtepomp: wij kennen de toestellen en hun pannes, van alle merken.'],
      ['users', 'Professionals en particulieren', 'Horeca, slagerijen, bakkerijen, voedingswinkels, industrie en kantoren, maar ook huizen en appartementen.'],
    ],
    certTitle: 'Erkenningen en merken',
    certLead: 'Werken met koelmiddelen is een gereglementeerde activiteit. FrigAirco beschikt over de vereiste erkenningen en werkt met de grote merken in koeling en airco.',
    certs: {
      'F-Gas': 'Technici gecertificeerd voor het werken met koelmiddelen',
      'Vinçotte': 'Erkenning afgeleverd door een onafhankelijke keuringsinstelling',
      'Bruxelles Environnement': 'Erkend koeltechnisch bedrijf (Leefmilieu Brussel)',
    },
    brandsTitle: 'De merken waarmee wij werken',
    reviewsTitle: 'Klantenbeoordelingen',
    reviewsLead: 'Wat onze klanten over FrigAirco zeggen op Google.',
    reviewsLink: 'Alle beoordelingen op Google bekijken',
    sectorsTitle: 'Onze klanten',
    sectors: ['Horeca', 'Slagerijen', 'Bakkerijen', 'Voedingswinkels', 'Industrie en logistiek', 'Kantoren', 'Particulieren'],
    galleryTitle: 'Onze realisaties',
    toComplete: 'nog in te vullen',
    notFoundTitle: 'Pagina niet gevonden',
    notFoundText: 'Deze pagina bestaat niet of is verplaatst.',
    notFoundBack: 'Terug naar de homepagina',
  },

  home: {
    title: 'FrigAirco | Koeltechnicus in België, herstelling 24/7',
    desc: 'Erkend koeltechnicus in België: herstelling koelcel, onderhoud airco, installatie warmtepomp. Bereikbaar 24 uur per dag, 7 dagen per week.',
    badge: 'Erkend koeltechnicus · Herstelling 24/7',
    h1: 'Uw koeltechnicus in België, <em>24u/24 en 7d/7</em>',
    lead: 'Herstelling koelcel, onderhoud airco, installatie warmtepomp, onderhoud commerciële en industriële koeling: FrigAirco komt langs in Vlaanderen, Brussel en Wallonië, voor professionals en particulieren.',
    checks: ['Interventie in heel België', 'Professionals en particulieren', 'F-gassen-gecertificeerde technici', 'Alle merken'],
    stats: [['24/24', 'Herstelling dag en nacht'], ['7/7', 'Weekends en feestdagen'], ['+10 jaar', 'ervaring'], ['F-Gas', 'Gecertificeerde technici']],
    pickerTitle: 'Welk toestel is in panne?',
    pickerNote: 'Kies uw toestel of stuur ons meteen een bericht.',
    servicesTitle: 'Onze diensten voor koeling en airco',
    servicesLead: 'Drie vakgebieden, één aanspreekpunt voor al uw koel- en airco-installaties.',
    equipTitle: 'Al uw koel- en airco-installaties',
    equipLead: 'Kies uw toestel voor meer uitleg over herstelling, onderhoud en installatie.',
    faq: [
      ['Is FrigAirco echt 24 uur per dag en 7 dagen per week bereikbaar?', 'Ja. Voor de herstelling van koelkast, koelcel en airco zijn wij dag en nacht bereikbaar, ook in het weekend en op feestdagen.'],
      ["In welke regio's komen jullie langs?", 'In Vlaanderen, Brussel en Wallonië: Antwerpen, Gent, Leuven, Mechelen, Hasselt, Kortrijk, Henegouwen, Waals-Brabant, Luik, Namen, de provincie Luxemburg en omgeving.'],
      ['Aan welke toestellen werken jullie?', 'Koelcellen en vriescellen, diepvriezers, professionele koelkasten, barkoelkasten en koelwerkbanken, bakkerij- en slagerijtoonbanken, koelvitrines, diepvrieskisten, snelkoelers, chillers, airco en warmtepompen.'],
      ['Werken jullie ook voor particulieren?', 'Ja. Wij verzorgen de installatie, het onderhoud en de herstelling van airco en warmtepompen bij particulieren, naast commerciële en industriële koeling voor professionals.'],
      ['Zijn uw technici erkend?', 'Ja. Onze koeltechnici zijn gecertificeerd voor het werken met F-gassen en het bedrijf is erkend als koeltechnisch bedrijf.'],
      ['Hoe vraag ik een offerte aan?', 'Vul het contactformulier in, bel ons of stuur een WhatsApp-bericht met een beschrijving van uw vraag. Wij nemen snel contact op.'],
    ],
  },

  actions: {
    depannage: {
      slug: 'herstelling',
      nav: 'Herstelling',
      name: 'Herstelling en depannage',
      listKey: 'faults',
      hub: {
        title: 'Herstelling koelcel, koelkast en airco 24/7 | FrigAirco',
        desc: 'Herstelling koelcel, koelkast, airco, warmtepomp, koelvitrine en chiller. Erkende koeltechnici, 24/7 bereikbaar in heel België.',
        h1: 'Herstelling koelkast, koelcel en airco – 24/7',
        cardTitle: 'Herstelling koeling en airco 24/7',
        lead: 'Een koelpanne wacht niet. FrigAirco verzorgt de herstelling en depannage van uw koel- en airco-installaties, dag en nacht, ook in het weekend en op feestdagen, in heel België.',
        card: 'Koelcel valt uit, koelkast koelt niet meer, airco in panne: een koeltechnicus die dag en nacht bereikbaar is.',
      },
      pair: (e) => `Herstelling ${e.name}`,
      title: (e) => fit(62, `Herstelling ${e.name} 24/7 in België | FrigAirco`, `Herstelling ${e.name} 24/7 | FrigAirco`),
      desc: (e) => kwFit(e, ': ', (k) => `Dringende herstelling ${e.name}, 24/7 in heel België${k}. Erkende koeltechnici, snel antwoord.`),
      h1: (e) => `Herstelling ${e.name} 24/7`,
      lead: (e) => `${cap(e.your)} valt uit? Onze koeltechnici komen 24 uur per dag en 7 dagen per week langs in Vlaanderen, Brussel en Wallonië voor de herstelling en depannage van ${e.your}: diagnose ter plaatse, reparatie en heropstart.`,
      listTitle: (e) => `Herstelling ${e.name}: de meest voorkomende pannes`,
      stepsTitle: (e) => `Hoe verloopt een herstelling ${e.name}?`,
      steps: [
        ['U belt of stuurt een WhatsApp', 'Beschrijf de panne: wij antwoorden snel, op elk uur.'],
        ['Diagnose ter plaatse', 'De technicus zoekt de oorzaak van de panne en legt uit wat er moet gebeuren.'],
        ['Reparatie', 'Vervanging van het defecte onderdeel, herstelling van het lek, bijvullen van koelmiddel indien nodig.'],
        ['Heropstart', 'Controle van de temperaturen en advies om een nieuwe panne te vermijden.'],
      ],
      faq: (e) => [
        [`Komen jullie 's nachts en in het weekend voor een herstelling ${e.name}?`, `Ja. De herstelling ${e.name} is 24 uur per dag en 7 dagen per week mogelijk, ook op feestdagen. Bel ons of stuur een WhatsApp-bericht.`],
        [`In welke regio's doen jullie de herstelling ${e.name}?`, 'In heel België: Vlaanderen, Brussel en Wallonië.'],
        ['Wat kan ik doen in afwachting van de technicus?', 'Noteer de foutcode of de temperatuur op het display, start het toestel niet meerdere keren na elkaar opnieuw op en houd bij voedselkoeling de deuren dicht om de koude te bewaren.'],
      ],
    },
    entretien: {
      slug: 'onderhoud',
      nav: 'Onderhoud',
      name: 'Onderhoud',
      listKey: 'upkeep',
      hub: {
        title: 'Onderhoud koelcel, koelkast en airco | FrigAirco',
        desc: 'Onderhoud airco, onderhoud koelcel, onderhoud warmtepomp en commerciële koeling. Eenmalig onderhoud of onderhoudscontract, in heel België.',
        h1: 'Onderhoud koelkast, koelcel en airco',
        cardTitle: 'Onderhoud koeling en airco',
        lead: 'Regelmatig onderhoud voorkomt de meeste pannes, verlaagt het verbruik en verlengt de levensduur van uw toestellen. FrigAirco verzorgt eenmalig onderhoud en onderhoudscontracten voor uw koel- en airco-installaties.',
        card: 'Eenmalig onderhoud of onderhoudscontract: minder pannes, lager verbruik, controles in orde.',
      },
      pair: (e) => `Onderhoud ${e.name}`,
      title: (e) => fit(62, `Onderhoud ${e.name} en onderhoudscontract in België | FrigAirco`, `Onderhoud ${e.name} en onderhoudscontract | FrigAirco`, `Onderhoud ${e.name} | FrigAirco`),
      desc: (e) => kwFit(e, ': ', (k) => `Onderhoud ${e.name} door erkende koeltechnici${k}. Eenmalig onderhoud of onderhoudscontract, in heel België.`),
      h1: (e) => `Onderhoud ${e.name}`,
      lead: (e) => `Regelmatig onderhoud van ${e.your} betekent minder pannes, een lager verbruik en een toestel dat langer meegaat. FrigAirco verzorgt eenmalig onderhoud en onderhoudscontracten, voor professionals en particulieren.`,
      listTitle: (e) => `Wat omvat het onderhoud ${e.name}?`,
      extra: (e) => [`Onderhoudscontract ${e.name}`, `Met een onderhoudscontract voor ${e.your} worden de bezoeken vooraf ingepland en de controles bij elk bezoek genoteerd. De frequentie leggen we samen met u vast, afhankelijk van het toestel en het gebruik.`],
      stepsTitle: (e) => `Hoe verloopt het onderhoud ${e.name}?`,
      steps: [
        ['Afspraak', 'Wij kiezen een datum die uw activiteit zo weinig mogelijk stoort.'],
        ['Bezoek van de technicus', 'Reiniging, controles en afstellingen volgens de lijst van uw toestel.'],
        ['Verslag', 'U weet wat er gedaan is en waarop u moet letten.'],
        ['Opvolging', 'Met een contract is het volgende bezoek al ingepland.'],
      ],
      faq: (e) => [
        [`Hoe vaak is onderhoud ${e.name} nodig?`, 'Dat hangt af van het toestel en het gebruik. Eén beurt per jaar is een gangbaar minimum; installaties die continu draaien of in een vette of stoffige omgeving staan, vragen vaker onderhoud. De frequentie leggen we samen met u vast.'],
        [`Is onderhoud ${e.name} verplicht?`, 'Boven een bepaalde hoeveelheid koelmiddel legt de F-gassenregelgeving periodieke lekdichtheidscontroles op, uitgevoerd door een gecertificeerde technicus. Wij vertellen u wat voor uw installatie geldt.'],
        [`Bieden jullie een onderhoudscontract ${e.name} aan?`, `Ja. Het onderhoudscontract ${e.name} voorziet geplande bezoeken en opvolging van de installatie. Vraag een offerte aan.`],
      ],
    },
    installation: {
      slug: 'installatie-montage',
      nav: 'Installatie',
      name: 'Installatie en montage',
      listKey: 'setup',
      hub: {
        title: 'Installatie en montage koelcel, airco en warmtepomp | FrigAirco',
        desc: 'Installatie koelcel, montage airco, installatie warmtepomp, koelvitrine en chiller. Studie, montage en inbedrijfstelling door erkende koeltechnici.',
        h1: 'Installatie en montage koelcel, airco en warmtepomp',
        cardTitle: 'Installatie en montage koeling en airco',
        lead: 'Een goed gedimensioneerde en goed gemonteerde installatie verbruikt minder en valt minder vaak uit. FrigAirco bestudeert uw behoefte, levert het materiaal en verzorgt de montage en de inbedrijfstelling.',
        card: 'Studie, levering, montage en inbedrijfstelling van uw koel- en airco-installaties.',
      },
      pair: (e) => `Installatie ${e.name}`,
      title: (e) => fit(62, `Installatie en montage ${e.name} in België | FrigAirco`, `Installatie en montage ${e.name} | FrigAirco`),
      desc: (e) => kwFit(e, ': ', (k) => `Installatie en montage ${e.name} door erkende koeltechnici${k}. Studie, offerte en inbedrijfstelling in heel België.`),
      h1: (e) => `Installatie en montage ${e.name}`,
      lead: (e) => `Nieuw project of vervanging van een toestel dat aan het einde van zijn levensduur is: FrigAirco verzorgt de installatie ${e.name} van studie tot inbedrijfstelling, met een verzorgde montage door erkende koeltechnici.`,
      listTitle: (e) => `Installatie ${e.name}: de stappen`,
      stepsTitle: (e) => `Uw project montage ${e.name}, stap voor stap`,
      steps: [
        ['Bezoek en studie', 'Wij bekijken de ruimte, uw beperkingen en wat u echt nodig hebt.'],
        ['Offerte', 'Een duidelijke offerte, met het voorgestelde materiaal en de geplande werken.'],
        ['Plaatsing en aansluiting', 'Plaatsing, aansluitingen en afwerking door onze technici.'],
        ['Inbedrijfstelling', 'Tests, afstellingen en uitleg over het gebruik.'],
      ],
      faq: (e) => [
        [`Wat kost een installatie ${e.name}?`, 'De prijs hangt af van het vermogen, het gekozen materiaal en de situatie ter plaatse. Wij maken een offerte na studie van uw behoefte.'],
        ['Welke merken installeren jullie?', 'Wij werken onder meer met Daikin, Mitsubishi Electric, Fujitsu, Bitzer en Danfoss, en verzorgen ook het onderhoud en de herstelling van andere merken.'],
        [`Doen jullie ook het onderhoud na de montage ${e.name}?`, `Ja. Na de installatie kunnen wij het onderhoud ${e.name} verzorgen, net als de herstelling, 24 uur per dag en 7 dagen per week.`],
      ],
    },
  },

  equipment: {
    coldroom: {
      slug: 'koelcel',
      label: 'Koelcel',
      name: 'koelcel',
      title: 'Koelcel en vriescel',
      your: 'uw koelcel',
      kw: ['positieve koelcel', 'vriescel', 'diepvriezer', 'diepvriescel'],
      short: 'Koelcellen, vriescellen en diepvriezers voor horeca, handel en industrie.',
      intro: 'Een koelcel die uitvalt, brengt uw goederen binnen enkele uren in gevaar. FrigAirco verzorgt positieve koelcellen (0 tot +8 °C), vriescellen en diepvriezers (tot −25 °C), ongeacht merk en volume.',
      faults: [
        'Koelcel die niet meer op temperatuur komt of een schommelende temperatuur heeft',
        'Vriescel of diepvriezer die aanvriest: verdamper vol ijs, ontdooiing defect',
        'Compressor die niet meer start, de zekering doet springen of continu draait',
        'Koelmiddellek, te weinig gas',
        'Deur, dichtingen of scharnieren die niet meer sluiten, temperatuuralarm',
      ],
      upkeep: [
        'Reiniging van condensor en verdamper',
        'Lekdichtheidscontrole van het circuit en controle van de werkdrukken',
        'Controle van ontdooiing, ventilatoren en condensafvoer',
        'Controle van deurdichtingen, scharnieren en kaderverwarming bij vriescellen',
        'Temperatuurmeting en afstelling van de regelaar',
      ],
      setup: [
        'Studie van volume, temperaturen en op te slaan producten',
        'Montage van isolatiepanelen, deur en vloer',
        'Installatie van koelgroep en verdamper',
        'Aansluiting, vacumeren, vullen met koelmiddel en inbedrijfstelling',
        'Afstelling van de regelaar en uitleg over het gebruik',
      ],
    },
    aircon: {
      slug: 'airco',
      label: 'Airco',
      name: 'airco',
      title: 'Airco en airconditioning',
      your: 'uw airco',
      kw: ['airconditioning', 'klimaatregeling', 'split en multisplit', 'omkeerbare airco'],
      short: 'Airco en omkeerbare airconditioning voor woningen, kantoren, winkels en horeca.',
      intro: 'Airco, airconditioning of klimaatregeling: FrigAirco verzorgt wandunits, consoles, cassettes en kanaalunits, in mono- en multisplit, bij particulieren en professionals.',
      faults: [
        'Airco die niet meer koelt of verwarmt',
        'Airco die lekt: water aan de binnenunit, verstopte condensafvoer',
        'Foutcode op het display, knipperend lampje, afstandsbediening reageert niet',
        'Onaangename geur of abnormaal geluid',
        'Buitenunit die niet start, te weinig koelmiddel',
      ],
      upkeep: [
        'Reiniging en ontsmetting van filters en binnenunit',
        'Reiniging van de warmtewisselaar van de buitenunit',
        'Lekdichtheidscontrole en controle van de drukken',
        'Controle van de condensafvoer',
        'Test in koel- en verwarmingsmodus, controle van de uitblaastemperaturen',
      ],
      setup: [
        'Bezoek en advies: vermogen, plaats van de units, mono- of multisplit',
        'Montage van binnen- en buitenunit',
        'Koelleidingen, condensafvoer en elektrische voeding',
        'Vacumeren, inbedrijfstelling en lekdichtheidscontrole',
        'Uitleg over de afstandsbediening en de instellingen',
      ],
    },
    heatpump: {
      slug: 'warmtepomp',
      label: 'Warmtepomp',
      name: 'warmtepomp',
      title: 'Warmtepomp',
      your: 'uw warmtepomp',
      kw: ['lucht-lucht warmtepomp', 'lucht-water warmtepomp', 'omkeerbare warmtepomp'],
      short: 'Lucht-lucht en lucht-water warmtepompen om zuiniger te verwarmen en te koelen.',
      intro: 'Een warmtepomp werkt met een koelcircuit: dat is het vak van de koeltechnicus. FrigAirco werkt aan lucht-lucht en lucht-water warmtepompen, voor verwarming, koeling en warm water.',
      faults: [
        'Warmtepomp die niet meer of slecht verwarmt',
        'Buitenunit vol ijs, ontdooiing werkt niet meer',
        'Foutcode, hogedruk- of lagedrukbeveiliging',
        'Abnormaal geluid of trillingen van compressor of ventilator',
        'Stijgend stroomverbruik, te weinig koelmiddel',
      ],
      upkeep: [
        'Reiniging van verdamper en buitenunit',
        'Lekdichtheidscontrole van het koelcircuit',
        'Controle van drukken, temperaturen en ontdooiing',
        'Controle van elektrische aansluitingen en beveiligingen',
        'Controle van filters en instellingen voor een goed rendement',
      ],
      setup: [
        'Studie van de warmtebehoefte en keuze van het vermogen',
        'Montage van buitenunit en binnenunits',
        'Koeltechnische en elektrische aansluitingen',
        'Inbedrijfstelling, afstelling en lekdichtheidscontrole',
        'Uitleg over de regeling en de juiste instellingen',
      ],
    },
    fridge: {
      slug: 'professionele-koelkast',
      label: 'Koelkast',
      name: 'koelkast',
      title: 'Koelkast, barkoelkast en koelwerkbank',
      your: 'uw koelkast',
      kw: ['professionele koelkast', 'barkoelkast', 'koelwerkbank', 'diepvrieskist', 'vrieskast'],
      short: 'Professionele koelkasten, barkoelkasten, koelwerkbanken, diepvrieskisten en vrieskasten.',
      intro: 'In een keuken, bar of winkel draait de koelkast zonder onderbreking. FrigAirco verzorgt professionele koelkasten, barkoelkasten, koelwerkbanken, diepvrieskisten en vrieskasten.',
      faults: [
        'Koelkast die niet of te weinig koelt',
        'Barkoelkast of koelwerkbank met ijsvorming of waterlek',
        'Luidruchtige compressor, die klikt of niet meer start',
        'Defecte thermostaat, voeler of regelaar',
        'Ventilator valt uit, versleten deurdichtingen, diepvrieskist die haar temperatuur niet houdt',
      ],
      upkeep: [
        'Stofvrij maken en reinigen van de condensor',
        'Controle van ventilatoren, thermostaat en voelers',
        'Controle en vervanging van deurdichtingen',
        'Reiniging van de dooiwaterafvoer',
        'Controle van temperaturen en koelmiddelvulling',
      ],
      setup: [
        'Advies over het juiste model: barkoelkast, koelwerkbank, koelkast of diepvrieskist',
        'Levering, plaatsing en waterpas stellen',
        'Montage en aansluiting van externe koelgroepen indien nodig',
        'Inbedrijfstelling en afstelling van de temperaturen',
        'Reglementaire terugwinning van het koelmiddel uit het oude toestel',
      ],
    },
    display: {
      slug: 'koelvitrine',
      label: 'Koelvitrine',
      name: 'koelvitrine',
      title: 'Koelvitrine, bakkerij- en slagerijtoonbank',
      your: 'uw koelvitrine',
      kw: ['bakkerijtoonbank', 'slagerijtoonbank', 'koeltoonbank', 'patisserievitrine'],
      short: 'Koelvitrines, bakkerijtoonbanken en slagerijtoonbanken: uw producten mooi gepresenteerd, op de juiste temperatuur.',
      intro: 'Een koelvitrine of slagerijtoonbank moet producten koel houden en ze tegelijk mooi tonen. FrigAirco werkt aan koelvitrines, bakkerij- en patisserietoonbanken, slagerijtoonbanken en zelfbedieningsmeubelen.',
      faults: [
        'Koelvitrine die haar temperatuur niet meer houdt',
        'Aangedampte ruiten of condensatie',
        'Slagerijtoonbank die aanvriest, verdamper geblokkeerd door ijs',
        'Water onder de toonbank, volle condensbak',
        'Ventilatie, verlichting of regelaar defect',
      ],
      upkeep: [
        'Reiniging van condensor, verdamper en luchtroosters',
        'Controle van ontdooiing en condensafvoer',
        'Controle van ventilatoren en luchtgordijn',
        'Controle van de temperatuur van de uitgestalde producten',
        'Lekdichtheidscontrole en controle van de koelmiddelvulling',
      ],
      setup: [
        'Keuze van bakkerijtoonbank, slagerijtoonbank of vitrine volgens uw producten',
        'Montage en plaatsing in uw winkel',
        'Aansluiting op een ingebouwde of externe koelgroep',
        'Inbedrijfstelling en afstelling van de temperaturen',
        'Eindcontrole voor het vullen met producten',
      ],
    },
    blast: {
      slug: 'snelkoeler',
      label: 'Snelkoeler',
      name: 'snelkoeler',
      title: 'Snelkoeler',
      your: 'uw snelkoeler',
      kw: ['blast chiller', 'snelvriezer', 'snelkoelcel'],
      short: 'Snelkoelers en snelvriezers om de koudeketen in de keuken te respecteren.',
      intro: 'De snelkoeler brengt uw bereidingen in zeer korte tijd van kooktemperatuur naar koeling, zoals de voedselhygiëne vraagt. Valt hij uit, dan ligt de hele keukenproductie stil.',
      faults: [
        'Koelcyclus die te lang duurt of niet eindigt',
        'Doeltemperatuur wordt nooit bereikt',
        'Defecte kernvoeler, foutmelding op het display',
        'Aangevroren verdamper, ventilator valt uit',
        'Compressor die de zekering doet springen of niet meer start',
      ],
      upkeep: [
        'Reiniging van condensor en verdamper',
        'Controle van de kernvoeler en de ruimtevoelers',
        'Controle van deurdichtingen en ontdooiing',
        'Controle van de afkoeltijden',
        'Lekdichtheidscontrole van het koelcircuit',
      ],
      setup: [
        'Keuze van de capaciteit volgens uw productie',
        'Plaatsing en montage in de keuken',
        'Elektrische aansluiting en waterafvoer',
        'Inbedrijfstelling en test van een volledige cyclus',
        "Uitleg over de koel- en vriesprogramma's",
      ],
    },
    refrigeration: {
      slug: 'commerciele-industriele-koeling',
      label: 'Koelinstallatie',
      name: 'commerciële en industriële koeling',
      title: 'Commerciële en industriële koeling',
      your: 'uw koelinstallatie',
      kw: ['commerciële koeling', 'industriële koeling', 'koelcentrale', 'condensatiegroep'],
      short: 'Koelinstallaties voor supermarkten, voedingswinkels, werkplaatsen, magazijnen en industrie.',
      intro: 'Supermarkt, uitsnijderij, logistiek magazijn of productiesite: commerciële en industriële koeling vraagt om zorgvuldig gedimensioneerde en goed opgevolgde installaties. FrigAirco verzorgt koelcentrales, condensatiegroepen, verdampers en koelmeubelen.',
      faults: [
        'Koelcentrale of condensatiegroep in storing',
        'Compressor in hogedruk- of lagedrukbeveiliging',
        'Koelmiddellek in het leidingnet',
        'Verdamper vol ijs, ontdooiing defect',
        'Regeling, expansieventiel of schakelkast defect',
      ],
      upkeep: [
        'Periodieke lekdichtheidscontroles volgens de F-gassenregelgeving',
        'Bijhouden van het logboek van de installatie',
        'Reiniging van condensors en verdampers',
        'Controle van compressoren, oliepeil en drukken',
        'Controle van regeling, beveiligingen en alarmen',
      ],
      setup: [
        'Koeltechnische studie en dimensionering van de installatie',
        'Montage van groepen, centrales, verdampers en leidingen',
        'Elektrische aansluiting en regeling',
        'Lekdichtheidstest, vacumeren en inbedrijfstelling',
        'Overhandiging van het dossier en het logboek van de installatie',
      ],
    },
    chiller: {
      slug: 'chiller',
      label: 'Chiller',
      name: 'chiller',
      title: 'Chiller en ijswatermachine',
      your: 'uw chiller',
      kw: ['ijswatermachine', 'waterkoeler', 'industriële koelgroep'],
      short: 'Chillers en ijswatermachines voor industriële processen en de klimatisatie van gebouwen.',
      intro: 'De chiller of ijswatermachine levert de koude voor een industrieel proces of voor de klimatisatie van een gebouw. Een panne kan een productielijn stilleggen: FrigAirco werkt aan lucht- en watergekoelde chillers.',
      faults: [
        'Chiller in hogedruk- of lagedrukalarm',
        'Storing in het waterdebiet: pomp of stromingsschakelaar',
        'Compressor die niet start of uitschakelt',
        'Te hoge wateruittredetemperatuur',
        'Koelmiddellek, vervuilde of bevroren warmtewisselaar',
      ],
      upkeep: [
        'Reiniging van condensors en controle van de warmtewisselaars',
        'Lekdichtheidscontrole van het koelcircuit',
        'Controle van drukken, oliepeil en stroomopname',
        'Controle van het watercircuit: debiet, filters, vorstbeveiliging',
        'Test van beveiligingen en regeling',
      ],
      setup: [
        'Dimensionering volgens het vereiste koelvermogen',
        'Plaatsing en montage van de chiller',
        'Hydraulische en elektrische aansluitingen',
        'Inbedrijfstelling en afstelling van de regeling',
        'Belastingstests en overhandiging van de bedieningsinstructies',
      ],
    },
  },

  zone: {
    title: (z) => fit(62, `Koeltechnicus ${z.loc}: herstelling koeling en airco 24/7 | FrigAirco`, `Koeltechnicus ${z.loc}: herstelling koeling 24/7 | FrigAirco`, `Koeltechnicus ${z.loc} 24/7 | FrigAirco`),
    desc: (z) => `Koeltechnicus ${z.loc}: herstelling koelcel, onderhoud airco, installatie warmtepomp. Bereikbaar 24 uur per dag, 7 dagen per week.`,
    h1: (z) => `Koeltechnicus ${z.loc}`,
    sub: 'Herstelling koelcel, koelkast en airco – 24/7',
    lead: (z) => `${z.ctx} FrigAirco komt ${z.loc} langs voor de herstelling, het onderhoud en de installatie van uw koel- en airco-installaties, bij professionals en particulieren.`,
    servicesTitle: (z) => `Onze diensten voor koeling en airco ${z.loc}`,
    nearTitle: (z) => `Gemeenten rond ${z.name}`,
    nearLead: (z) => `Wij komen langs ${z.loc} en in de omliggende gemeenten:`,
    relatedTitle: "Regio's in de buurt",
    faq: (z) => [
      [`Hoe snel zijn jullie ter plaatse ${z.loc}?`, `Wij antwoorden snel, 24 uur per dag en 7 dagen per week, en plannen de verplaatsing ${z.loc} zo snel mogelijk volgens de dringendheid.`],
      [`Welke toestellen herstellen jullie ${z.loc}?`, 'Koelcellen en vriescellen, diepvriezers, professionele koelkasten, barkoelkasten en koelwerkbanken, koelvitrines, bakkerij- en slagerijtoonbanken, snelkoelers, chillers, airco en warmtepompen.'],
      [`Komen jullie ook in de omgeving van ${z.name}?`, `Ja: ${z.near.join(', ')} en de omliggende gemeenten.`],
    ],
  },

  zonesPage: {
    title: 'Koeltechnicus in Vlaanderen, Brussel en Wallonië | FrigAirco',
    desc: 'FrigAirco komt langs in heel België: Antwerpen, Gent, Leuven, Mechelen, Hasselt, Kortrijk, Brussel, Henegouwen, Waals-Brabant, Luik en Namen.',
    h1: 'Koeltechnicus in heel België',
    lead: 'Herstelling koelcel, onderhoud airco, installatie warmtepomp: kies uw regio of stad.',
  },

  contact: {
    title: 'Contact en offerte | FrigAirco, koeltechnicus 24/7',
    desc: 'Contacteer FrigAirco per telefoon, WhatsApp of formulier voor een herstelling van koeling of airco, een onderhoud of een offerte. Snel antwoord, 24/7.',
    h1: 'Contact en offerteaanvraag',
    lead: 'Dringend? Bel ons of stuur een WhatsApp-bericht: dat gaat het snelst. Voor een offerte of een vraag gebruikt u het formulier.',
    formTitle: 'Stuur ons uw aanvraag',
    phoneLabel: 'Telefoon',
    phoneNote: 'Dringende herstellingen 24/7',
    waLabel: 'WhatsApp',
    waNote: 'Stuur een foto van de panne',
    mailLabel: 'E-mail',
    mailNote: 'Offertes en vragen',
    areaLabel: 'Werkgebied',
    areaNote: 'Vlaanderen, Brussel en Wallonië',
  },

  form: {
    name: 'Naam',
    phone: 'Telefoon',
    email: 'E-mail',
    city: 'Postcode en gemeente',
    type: 'Uw aanvraag',
    types: ['Dringende herstelling', 'Onderhoud of onderhoudscontract', 'Installatie of montage', 'Offerteaanvraag', 'Andere'],
    equip: 'Betrokken toestel',
    equipOther: 'Andere',
    message: 'Bericht',
    messageHint: 'Beschrijf de panne of uw project',
    consent: 'Ik ga ermee akkoord dat mijn gegevens worden gebruikt om mijn aanvraag te beantwoorden.',
    send: 'Aanvraag verzenden',
    sending: 'Bezig met verzenden…',
    ok: 'Bedankt, uw aanvraag is verzonden. Wij nemen snel contact met u op.',
    error: 'Het verzenden is niet gelukt. Bel ons of stuur een WhatsApp-bericht.',
    mailto: 'Uw e-mailprogramma wordt geopend met de aanvraag klaar om te verzenden.',
    subject: 'Aanvraag via de website FrigAirco',
  },

  blog: {
    title: 'Advies van de koeltechnicus: koeling en airco | FrigAirco',
    desc: 'Praktisch advies over koelcel, professionele koelkast, airco en warmtepomp: veelvoorkomende pannes, onderhoud en goede gewoontes.',
    h1: 'Advies van de koeltechnicus',
    lead: 'Veelvoorkomende pannes, onderhoud en goede gewoontes: wat u moet weten over uw koel- en airco-installaties.',
  },

  articles: [
    {
      key: 'coldroom-not-cooling',
      slug: 'koelcel-koelt-niet-meer',
      date: '2026-10-04',
      title: 'Koelcel koelt niet meer: wat controleren voor u belt',
      desc: 'Uw koelcel koelt niet meer? De eenvoudige controles voor u de herstelling koelcel belt, en de fouten die u beter vermijdt.',
      intro: 'Een koelcel waarvan de temperatuur stijgt, brengt uw voorraad in gevaar. Voor u de herstelling koelcel belt, kunnen enkele eenvoudige controles de installatie soms opnieuw op gang brengen, of de technicus op zijn minst de juiste informatie geven.',
      sections: [
        ['1. De deur en de dichtingen', 'Een slecht gesloten deur of een beschadigde dichting laat warme en vochtige lucht binnen. Controleer of de deur goed sluit en of niets ze blokkeert.'],
        ['2. De regelaar en de voeding', 'Kijk naar het display: per ongeluk gewijzigde instelling, alarmcode, zwart scherm? Controleer ook de zekering in de elektriciteitskast.'],
        ['3. IJs op de verdamper', 'Een verdamper vol ijs laat geen lucht meer door. Dat wijst vaak op een defecte ontdooiing of een deur die te vaak openstaat. Breek het ijs niet met gereedschap: u kunt de warmtewisselaar doorboren.'],
        ['4. Een vervuilde condensor', 'Buiten de cel voert de condensor de warmte af. Zit hij vol stof of vet, dan raakt de groep oververhit en schakelt hij uit.'],
        ['Wanneer een koeltechnicus bellen?', 'Start de compressor niet, springt de zekering of blijft de temperatuur stijgen, dring dan niet aan. Houd de deur dicht, verplaats gevoelige producten indien mogelijk en bel de herstelling koelcel: FrigAirco is 24 uur per dag en 7 dagen per week bereikbaar.'],
      ],
      link: 'combo:depannage:coldroom',
    },
    {
      key: 'aircon-maintenance',
      slug: 'hoe-vaak-onderhoud-airco',
      date: '2026-10-04',
      title: 'Onderhoud airco: hoe vaak en waarom?',
      desc: 'Hoe vaak is onderhoud airco nodig? Wat u zelf kunt doen, wat de technicus doet en wat de regelgeving voorschrijft.',
      intro: 'Een airco die nooit onderhouden wordt, koelt minder goed, verbruikt meer en gaat uiteindelijk onaangenaam ruiken. Dit moet u weten over het onderhoud airco.',
      sections: [
        ['Wat u zelf kunt doen', 'Reinig de filters van de binnenunit regelmatig, om de paar weken tijdens het gebruiksseizoen. Maak ook de buitenunit vrij: bladeren, stof en voorwerpen ervoor hinderen de luchtstroom.'],
        ['Wat de technicus doet', 'Het onderhoud airco door een koeltechnicus gaat verder: reiniging en ontsmetting van de binnenunit, reiniging van de buitenwarmtewisselaar, controle van de condensafvoer, controle van de drukken en van de lekdichtheid van het circuit.'],
        ['Hoe vaak?', 'Voor een woning is één onderhoud airco per jaar een goede basis. In een winkel, restaurant of kantoor waar de airco de hele dag draait, is vaker onderhoud aangewezen.'],
        ['En de verplichtingen?', 'Afhankelijk van de hoeveelheid koelmiddel in de installatie legt de F-gassenregelgeving periodieke lekdichtheidscontroles op door een gecertificeerde technicus. Met een onderhoudscontract airco hoeft u er niet meer aan te denken.'],
      ],
      link: 'combo:entretien:aircon',
    },
  ],

  legal: {
    title: 'Wettelijke vermeldingen | FrigAirco',
    h1: 'Wettelijke vermeldingen',
    blocks: (c) => [
      ['Uitgever van de website', `${c.legalName}<br>${c.address}<br>Ondernemingsnummer (KBO/btw): ${c.vat}<br>Telefoon: ${c.phone}<br>E-mail: ${c.email}`],
      ['Hosting', c.host],
      ['Intellectuele eigendom', 'De teksten, het logo en de vormgeving van deze website zijn eigendom van FrigAirco. De vermelde merken behoren toe aan hun respectieve eigenaars en worden ter informatie vermeld.'],
      ['Aansprakelijkheid', 'De informatie op deze website is louter indicatief en vervangt de diagnose van een technicus ter plaatse niet.'],
    ],
  },

  privacy: {
    title: 'Privacybeleid | FrigAirco',
    h1: 'Privacybeleid',
    blocks: (c) => [
      ['Verwerkingsverantwoordelijke', `${c.legalName}, ${c.address}. Contact: ${c.email}.`],
      ['Verzamelde gegevens', 'Wanneer u het contactformulier gebruikt, ontvangen wij de gegevens die u invult: naam, telefoon, e-mailadres, gemeente en bericht.'],
      ['Gebruik', 'Deze gegevens dienen uitsluitend om uw aanvraag te beantwoorden, een offerte op te maken en een interventie te plannen. Ze worden niet verkocht of doorgegeven aan derden.'],
      ['Bewaartermijn', 'Uw gegevens worden bewaard zolang dat nodig is voor de behandeling van uw aanvraag en de opvolging van de klantenrelatie, en daarna gewist.'],
      ['Cookies', 'Deze website gebruikt geen reclame- of trackingcookies.'],
      ['Uw rechten', 'U kunt inzage, verbetering of verwijdering van uw gegevens vragen door ons te schrijven. U kunt ook een klacht indienen bij de Gegevensbeschermingsautoriteit (www.gegevensbeschermingsautoriteit.be).'],
    ],
  },
};
